<section class="lp-landing-section container">
    <div class="lp-water-mark-floatting-container">
        <p class="lp-watter-mark--fitness">
            Fitness
        </p>
    </div>
    <div class="row lp-content-row">

        <div class="lp-landing-text-area col-12 col-md-5">
            <div class="lp-landing-text--content">
                <h1 class="lp-landing-text--title">
                    Encontre seu consultor <span>Fitness</span>
                </h1>
                <p class="lp-landing-text--message">
                    Encontre profissionais para te auxiliar na jornada fitness da melhor forma possível
                </p>
            </div>
            <div class="lp-landing-text--action-button-container">
                <button class="spot-btn-blue onhover-broom">
                    <span>Buscar Profissionais</span>
                </button>
                <!-- <button class="spot-primary-btn">Buscar Profissionais</button> -->
                <button class="spot-secondary-btn">Eu sou um Profissional</button>
            </div>
        </div>
        
        <div class="lp-landing-image-area col-12 col-md-4 ms-auto">
            <img src="/assets/img/model-1.png" alt="Modelos de academia" class="lp-landing-section--model-image">
        </div>
        
    </div>
    
</section>