<section class="lp-landing-section container">
    <div class="lp-water-mark-floatting-container">
        <p class="lp-watter-mark--fitness">
            Fitness
        </p>
    </div>
    <div class="row lp-landing-text-area">
        <div class="lp-landing-text--content  col-12 col-md-8 col-lg-7">
            <h1 class="lp-landing-text--title">
                Encontre seu consultor <span>Fitness</span>
            </h1>
            <p class="lp-landing-text--message">
                Encontre profissionais para te auxiliar na jornada fitness da melhor forma possível
            </p>
            <div class="lp-landing-text--action-button-container">
                <a href="/professional" class="spot-btn-blue onhover-broom">
                    <span>Buscar Profissionais</span>
                </a>
                <a href="/sign_up" class="spot-secondary-btn">Eu sou um Profissional</a>
            </div>
        </div>
        <div class="lp-landing-image-area col-12 col-md-4 ms-auto">
            <div class="lp-model-image-cover"></div>
            <img src="/assets/img/model-1.png" alt="Modelos de academia" class="lp-landing-section--model-image">
        </div>
    </div>
</section>

<section id="lpCategoriesSection">
    <div class="container-fluid">
        <div class="container">
            <div class="lp-categories-title-area row">
                <h1 class="lp-landing-text--title">Nossos Benefícios</h1>
                <p class="lp-landing-title-watermark">Benefícios</p>
            </div>
        </div>

        <div class="row lp-categories-slider-row">
            <div class="swiper lp-categories-swiper">
                <div class="swiper-wrapper">
                    <div class="swiper-slide lp-categories-swiper--item primary">
                        <a href="#">
                            <div class="lp-swiper-slide--item-container">
                                <img src="/assets/icons/helthIcon2.svg" class="lp-swiper-slide--item-icon" alt="">
                                <h1 class="lp-swiper-slide--item-title">Nuticinonista</h1>
                                <p class="lp-swiper-slide--item-text">
                                    Otimize sua saúde com um plano alimentar personalizado elaborado por um nutricionista especializado.
                                </p>
                            </div>
                        </a>
                    </div>
                    <div class="swiper-slide lp-categories-swiper--item">
                        <a href="#">
                            <div class="lp-swiper-slide--item-container">
                                <img src="/assets/icons/helthIcon2.svg" class="lp-swiper-slide--item-icon" alt="">
                                <h1 class="lp-swiper-slide--item-title">Nuticinonista</h1>
                                <p class="lp-swiper-slide--item-text">
                                    Otimize sua saúde com um plano alimentar personalizado elaborado por um nutricionista especializado.
                                </p>
                            </div>
                        </a>
                    </div>
                    <div class="swiper-slide lp-categories-swiper--item">
                        <a href="#">
                            <div class="lp-swiper-slide--item-container">
                                <img src="/assets/icons/helthIcon2.svg" class="lp-swiper-slide--item-icon" alt="">
                                <h1 class="lp-swiper-slide--item-title">Nuticinonista</h1>
                                <p class="lp-swiper-slide--item-text">
                                    Otimize sua saúde com um plano alimentar personalizado elaborado por um nutricionista especializado.
                                </p>
                            </div>
                        </a>
                    </div>
                    <div class="swiper-slide lp-categories-swiper--item">
                        <a href="#">
                            <div class="lp-swiper-slide--item-container">
                                <img src="/assets/icons/helthIcon2.svg" class="lp-swiper-slide--item-icon" alt="">
                                <h1 class="lp-swiper-slide--item-title">Nuticinonista</h1>
                                <p class="lp-swiper-slide--item-text">
                                    Otimize sua saúde com um plano alimentar personalizado elaborado por um nutricionista especializado.
                                </p>
                            </div>
                        </a>
                    </div>
                    <div class="swiper-slide lp-categories-swiper--item">
                        <a href="#">
                            <div class="lp-swiper-slide--item-container">
                                <img src="/assets/icons/helthIcon2.svg" class="lp-swiper-slide--item-icon" alt="">
                                <h1 class="lp-swiper-slide--item-title">Nuticinonista</h1>
                                <p class="lp-swiper-slide--item-text">
                                    Otimize sua saúde com um plano alimentar personalizado elaborado por um nutricionista especializado.
                                </p>
                            </div>
                        </a>
                    </div>
                        <div class="swiper-slide lp-categories-swiper--item">
                            <a href="#">
                                <div class="lp-swiper-slide--item-container">
                                    <img src="/assets/icons/helthIcon2.svg" class="lp-swiper-slide--item-icon" alt="">
                                    <h1 class="lp-swiper-slide--item-title">Nuticinonista</h1>
                                    <p class="lp-swiper-slide--item-text">
                                        Otimize sua saúde com um plano alimentar personalizado elaborado por um nutricionista especializado.
                                    </p>
                                </div>
                            </a>
                        </div>
                </div>
                <div class="lp-control-swiper-categorie-button lp-control-swiper-categorie-button-next"><i class="fa-solid fa-chevron-right"></i></div>
                <div class="lp-control-swiper-categorie-button lp-control-swiper-categorie-button-prev"><i class="fa-solid fa-chevron-left"></i></div>
            </div>
        </div>
    </div>
</section>

<section id="lpWelcomeSection">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-7 order-2 order-lg-1 d-flex justify-content-center">
                <div class="lp-welcome-content-images-container">
                    <img src="/assets/img/models/m1.png" alt="">
                    <img src="/assets/img/models/m2.png" alt="">
                    <img src="/assets/img/models/m3.png" alt="">
                </div>
            </div>
            <div class="col-12 col-lg-5 order-1 order-lg-2 lp-welcome-content-col">
                <h1 class="lp-landing-text--title">Leve suas <span> praticas saudaveis </span> para outro nível.</h1>
                <div class="lp-welcome-content-area">
                    <ul class="lp-welcome-content--list">
                        <li>
                            <img src="/assets/icons/checklist.svg" alt="">
                            <p>Exercicios personalizados</p>
                        </li>
                        <li>
                            <img src="/assets/icons/checklist.svg" alt="">
                            <p>Alimentacao para seu objetivo </p>
                        </li>
                        <li>
                            <img src="/assets/icons/checklist.svg" alt="">
                            <p>Melhore sua capacidade fisica</p>
                        </li>
                    </ul>
                </div>
                <div class="lp-welcome-action-button-container">
                    <a href="/professional" class="spot-btn-dark onhover-broom">
                        <span>Buscar Profissionais</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>

<section id="lpYouAreAProfessionalBanner">
    <div class="container">
        <div class="row spot-banner-container">
            <div class="col-12 col-md-8 col-xl-5 spot-banner-content">
                <h1 class="spot-banner-text--title">Você é um <span class="spot-text-orange"> profissional de fitness</span>? </h1>
                <p class="spot-banner-text--paragraph">
                    <span class="spot-text-orange"> Conecte-se com clientes </span> em busca de seus serviços especializados em consultoria de saúde e fitness
                </p>
            </div>
            <div class="col-12 col-md-4 ms-auto">
                <div class="spot-banner-action-container">
                    <a href="/sign_in" class="spot-btn-blue onhover-broom">
                        <span>Crie sua conta</span>
                    </a>

                </div>
            </div>
        </div>
    </div>
</section>

<section id="lpTestemonialsSection">
    <div class="container-fluid">
        <div class="container">
            <div class="lp-categories-title-area row">
                <h1 class="lp-landing-text--title">Avaliação de nossos usuários</h1>
                <p class="lp-landing-title-watermark">Feedback</p>
            </div>
        </div>

        <div class="row lp-testemonial-slider-row">
            <div class="swiper lp-testemonial-swiper">
                <div class="swiper-wrapper">
                    <div class="swiper-slide lp-testemonial-swiper--item">
                        <div class="container lp-testemonial-card--container">
                            <div class="row lp-testemonial-card--stars">
                                <img src="/assets/icons/star-filled.svg" alt="">
                                <img src="/assets/icons/star-filled.svg" alt="">
                                <img src="/assets/icons/star-filled.svg" alt="">
                                <img src="/assets/icons/star-filled.svg" alt="">
                                <img src="/assets/icons/star-filled.svg" alt="">
                            </div>

                            <div class="row lp-testemonial-card--text">
                                <p>Junte-se a este membro fitness, a melhor escolha que já fiz. Eles são muito profissionais e oferecem sugestões sobre quais alimentos e nutrição você pode consumir.</p>
                            </div>

                            <div class="row lp-testemonial-card--user">
                                <img class="lp-testimonial-card--user-image" src="/assets/img/devs/Natan.jpg" alt="">
                                <h3 class="lp-testimonial-card--user-name">Jonathan Edward</h3>
                                <p class="lp-testimonial-card--user-description">Office Worker</p>
                            </div>
                        </div>
                    </div>
                    <div class="swiper-slide lp-testemonial-swiper--item">
                        <div class="container lp-testemonial-card--container">
                            <div class="row lp-testemonial-card--stars">
                                <img src="/assets/icons/star-filled.svg" alt="">
                                <img src="/assets/icons/star-filled.svg" alt="">
                                <img src="/assets/icons/star-filled.svg" alt="">
                                <img src="/assets/icons/star-filled.svg" alt="">
                                <img src="/assets/icons/star-filled.svg" alt="">
                            </div>

                            <div class="row lp-testemonial-card--text">
                                <p>Junte-se a este membro fitness, a melhor escolha que já fiz. Eles são muito profissionais e oferecem sugestões sobre quais alimentos e nutrição você pode consumir.</p>
                            </div>

                            <div class="row lp-testemonial-card--user">
                                <img class="lp-testimonial-card--user-image" src="/assets/img/devs/Natan.jpg" alt="">
                                <h3 class="lp-testimonial-card--user-name">Jonathan Edward</h3>
                                <p class="lp-testimonial-card--user-description">Office Worker</p>
                            </div>
                        </div>
                    </div>
                    <div class="swiper-slide lp-testemonial-swiper--item">
                        <div class="container lp-testemonial-card--container">
                            <div class="row lp-testemonial-card--stars">
                                <img src="/assets/icons/star-filled.svg" alt="">
                                <img src="/assets/icons/star-filled.svg" alt="">
                                <img src="/assets/icons/star-filled.svg" alt="">
                                <img src="/assets/icons/star-filled.svg" alt="">
                                <img src="/assets/icons/star-filled.svg" alt="">
                            </div>

                            <div class="row lp-testemonial-card--text">
                                <p>Junte-se a este membro fitness, a melhor escolha que já fiz. Eles são muito profissionais e oferecem sugestões sobre quais alimentos e nutrição você pode consumir.</p>
                            </div>

                            <div class="row lp-testemonial-card--user">
                                <img class="lp-testimonial-card--user-image" src="/assets/img/devs/Natan.jpg" alt="">
                                <h3 class="lp-testimonial-card--user-name">Jonathan Edward</h3>
                                <p class="lp-testimonial-card--user-description">Office Worker</p>
                            </div>
                        </div>
                    </div>
                    <div class="swiper-slide lp-testemonial-swiper--item">
                        <div class="container lp-testemonial-card--container">
                            <div class="row lp-testemonial-card--stars">
                                <img src="/assets/icons/star-filled.svg" alt="">
                                <img src="/assets/icons/star-filled.svg" alt="">
                                <img src="/assets/icons/star-filled.svg" alt="">
                                <img src="/assets/icons/star-filled.svg" alt="">
                                <img src="/assets/icons/star-filled.svg" alt="">
                            </div>

                            <div class="row lp-testemonial-card--text">
                                <p>Junte-se a este membro fitness, a melhor escolha que já fiz. Eles são muito profissionais e oferecem sugestões sobre quais alimentos e nutrição você pode consumir.</p>
                            </div>

                            <div class="row lp-testemonial-card--user">
                                <img class="lp-testimonial-card--user-image" src="/assets/img/devs/Natan.jpg" alt="">
                                <h3 class="lp-testimonial-card--user-name">Jonathan Edward</h3>
                                <p class="lp-testimonial-card--user-description">Office Worker</p>
                            </div>
                        </div>
                    </div>
                    <div class="swiper-slide lp-testemonial-swiper--item">
                        <div class="container lp-testemonial-card--container">
                            <div class="row lp-testemonial-card--stars">
                                <img src="/assets/icons/star-filled.svg" alt="">
                                <img src="/assets/icons/star-filled.svg" alt="">
                                <img src="/assets/icons/star-filled.svg" alt="">
                                <img src="/assets/icons/star-filled.svg" alt="">
                                <img src="/assets/icons/star-filled.svg" alt="">
                            </div>

                            <div class="row lp-testemonial-card--text">
                                <p>Junte-se a este membro fitness, a melhor escolha que já fiz. Eles são muito profissionais e oferecem sugestões sobre quais alimentos e nutrição você pode consumir.</p>
                            </div>

                            <div class="row lp-testemonial-card--user">
                                <img class="lp-testimonial-card--user-image" src="/assets/img/devs/Natan.jpg" alt="">
                                <h3 class="lp-testimonial-card--user-name">Jonathan Edward</h3>
                                <p class="lp-testimonial-card--user-description">Office Worker</p>
                            </div>
                        </div>
                    </div>
                    <div class="swiper-slide lp-testemonial-swiper--item">
                        <div class="container lp-testemonial-card--container">
                            <div class="row lp-testemonial-card--stars">
                                <img src="/assets/icons/star-filled.svg" alt="">
                                <img src="/assets/icons/star-filled.svg" alt="">
                                <img src="/assets/icons/star-filled.svg" alt="">
                                <img src="/assets/icons/star-filled.svg" alt="">
                                <img src="/assets/icons/star-filled.svg" alt="">
                            </div>

                            <div class="row lp-testemonial-card--text">
                                <p>Junte-se a este membro fitness, a melhor escolha que já fiz. Eles são muito profissionais e oferecem sugestões sobre quais alimentos e nutrição você pode consumir.</p>
                            </div>

                            <div class="row lp-testemonial-card--user">
                                <img class="lp-testimonial-card--user-image" src="/assets/img/devs/Natan.jpg" alt="">
                                <h3 class="lp-testimonial-card--user-name">Jonathan Edward</h3>
                                <p class="lp-testimonial-card--user-description">Office Worker</p>
                            </div>
                        </div>
                    </div>
                 
                </div>
                <div class="lp-control-swiper-testemonial-button lp-control-swiper-testemonial-button-next"><i class="fa-solid fa-chevron-right"></i></div>
                <div class="lp-control-swiper-testemonial-button lp-control-swiper-testemonial-button-prev"><i class="fa-solid fa-chevron-left"></i></div>
            </div>
        </div>
    </div>
</section>

<section id="lpSubscribeSection">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="spot-subscribe-banner">
                    <h1 class="spot-subscribe-banner--title">Increva-se e fique por dentro</h1>
                    <p class="spot-subscribe-banner--text">Receba informações sobre novos profissionais </p>
                    <div class="spot-subscribe-banner--email-area">
                        <form action="/sign_up" method="post">
                            <input type="email" name="email" id="" placeholder="Insira seu e-mail" class="spot-subscribe-banner--input-email">

                            <button type="submit" class="spot-btn-dark onhover-broom">
                                <span>
                                    Inscreva-se
                                </span>
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>