<section class="lp-landing-section container">
    <div class="lp-water-mark-floatting-container">
        <p class="lp-watter-mark--fitness">
            Fitness
        </p>
    </div>
    <div class="row lp-landing-text-area">
        <div class="lp-landing-text--content  col-12 col-md-8 col-lg-7">
            <h1 class="lp-landing-text--title">
                Encontre seu consultor <span>Fitness</span>
            </h1>
            <p class="lp-landing-text--message">
                Encontre profissionais para te auxiliar na jornada fitness da melhor forma possível
            </p>
            <div class="lp-landing-text--action-button-container">
                <button class="spot-btn-blue onhover-broom">
                    <span>Buscar Profissionais</span>
                </button>
                <button class="spot-secondary-btn">Eu sou um Profissional</button>
            </div>
        </div>
        <div class="lp-landing-image-area col-12 col-md-4 ms-auto">
            <div class="lp-model-image-cover"></div>
            <img src="/assets/img/model-1.png" alt="Modelos de academia" class="lp-landing-section--model-image">
        </div>
    </div>
</section>

<section id="lpCategoriesSection">
    <div class="container-fluid">
        <div class="container">
            <div class="lp-categories-title-area row">
                <h1 class="lp-landing-text--title">Nossas Categorias</h1>
                <p class="lp-landing-title-watermark">Categorias</p>
            </div>
        </div>

        <div class="row lp-categories-slider-row">
            <div class="swiper lp-categories-swiper">
                <div class="swiper-wrapper">
                    <div class="swiper-slide lp-categories-swiper--item primary">
                        <a href="#">
                            <div class="lp-swiper-slide--item-container">
                                <img src="/assets/icons/helthIcon2.svg" class="lp-swiper-slide--item-icon" alt="">
                                <h1 class="lp-swiper-slide--item-title">Nuticinonista</h1>
                                <p class="lp-swiper-slide--item-text">
                                    Otimize sua saúde com um plano alimentar personalizado elaborado por um nutricionista especializado.
                                </p>
                            </div>
                        </a>
                    </div>
                    <div class="swiper-slide lp-categories-swiper--item">
                        <a href="#">
                            <div class="lp-swiper-slide--item-container">
                                <img src="/assets/icons/helthIcon2.svg" class="lp-swiper-slide--item-icon" alt="">
                                <h1 class="lp-swiper-slide--item-title">Nuticinonista</h1>
                                <p class="lp-swiper-slide--item-text">
                                    Otimize sua saúde com um plano alimentar personalizado elaborado por um nutricionista especializado.
                                </p>
                            </div>
                        </a>
                    </div>
                    <div class="swiper-slide lp-categories-swiper--item">
                        <a href="#">
                            <div class="lp-swiper-slide--item-container">
                                <img src="/assets/icons/helthIcon2.svg" class="lp-swiper-slide--item-icon" alt="">
                                <h1 class="lp-swiper-slide--item-title">Nuticinonista</h1>
                                <p class="lp-swiper-slide--item-text">
                                    Otimize sua saúde com um plano alimentar personalizado elaborado por um nutricionista especializado.
                                </p>
                            </div>
                        </a>
                    </div>
                    <div class="swiper-slide lp-categories-swiper--item">
                        <a href="#">
                            <div class="lp-swiper-slide--item-container">
                                <img src="/assets/icons/helthIcon2.svg" class="lp-swiper-slide--item-icon" alt="">
                                <h1 class="lp-swiper-slide--item-title">Nuticinonista</h1>
                                <p class="lp-swiper-slide--item-text">
                                    Otimize sua saúde com um plano alimentar personalizado elaborado por um nutricionista especializado.
                                </p>
                            </div>
                        </a>
                    </div>
                    <div class="swiper-slide lp-categories-swiper--item">
                        <a href="#">
                            <div class="lp-swiper-slide--item-container">
                                <img src="/assets/icons/helthIcon2.svg" class="lp-swiper-slide--item-icon" alt="">
                                <h1 class="lp-swiper-slide--item-title">Nuticinonista</h1>
                                <p class="lp-swiper-slide--item-text">
                                    Otimize sua saúde com um plano alimentar personalizado elaborado por um nutricionista especializado.
                                </p>
                            </div>
                        </a>
                    </div>
                        <div class="swiper-slide lp-categories-swiper--item">
                            <a href="#">
                                <div class="lp-swiper-slide--item-container">
                                    <img src="/assets/icons/helthIcon2.svg" class="lp-swiper-slide--item-icon" alt="">
                                    <h1 class="lp-swiper-slide--item-title">Nuticinonista</h1>
                                    <p class="lp-swiper-slide--item-text">
                                        Otimize sua saúde com um plano alimentar personalizado elaborado por um nutricionista especializado.
                                    </p>
                                </div>
                            </a>
                        </div>
                </div>
                <div class="lp-control-swiper-categorie-button lp-control-swiper-categorie-button-next"><i class="fa-solid fa-chevron-right"></i></div>
                <div class="lp-control-swiper-categorie-button lp-control-swiper-categorie-button-prev"><i class="fa-solid fa-chevron-left"></i></div>
            </div>
        </div>
    </div>
</section>