<fieldset id="form-step-4-container" class="form-step-container d-none">
    <div class="text-center">
        <h2 class="fs-3">Benefícios</h2>
        <p class="text-light">O que sua consultoria pode oferecer ao cliente.</p>
    </div>

    <div class="mt-3">
        <input type="hidden" name="form_step" value="4">

        <div id="benefits">
        </div>

        <button type="button" class="btn btn-success" id="add_benefit">
            <i class="fas fa-plus"></i> Adicionar Benefício
        </button>
    </div>
</fieldset>