<fieldset id="form-step-5-container" class="form-step-container d-none">
    <div class="text-center">
        <h2 class="fs-3">Planos e preços</h2>
        <p class="text-light">Planos, benefícios incluídos e mensalidades do respectivos planos.</p>
    </div>

    <div class="mt-3">
        <input type="hidden" name="form_step" value="5">

        <div id="plans">
        </div>

        <button type="button" class="btn btn-success" id="add_plan">
            <i class="fas fa-plus"></i> Adicionar Plano
        </button>
    </div>
</fieldset>