<div class="text-center">
    <h2 class="fs-3">Informações básicas</h2>
    <p class="text-light">Informações de identificação e contato com a consultoria </p>
</div>

<form action="/consulting/create" method="post" class="mt-3">
    <input type="hidden" name="form_step" value="1">

    <div class="mb-4">
        <label for="name" class="form-label">Nome da consultoria *</label>
        <input type="text" class="form-control" id="name" name="name">
        <div id="emailHelp" class="form-text text-subtitle">Nome da marca pela qual as pessoas te reconhecem</div>
    </div>

    <div class="mb-4">
        <label for="contact_email" class="form-label">Email de contato *</label>
        <input type="email" class="form-control" id="contact_email" name="contact_email">
    </div>

    <div class="mb-4">
        <label for="contact_phone" class="form-label">Telefone de contato</label>
        <input type="text" class="form-control" id="contact_phone" name="contact_phone">
    </div>

    <div class="mb-4">
        <label for="desc" class="form-label">Descrição</label>
        <textarea class="form-control" placeholder="Explique brevemente como funciona sua consultoria" id="desc" name="desc"></textarea>
    </div>

    <div class="form_actions mt-5">
        <button type="submit" class="btn btn-primary">Salvar e continuar</button>
    </div>
</form>