<fieldset id="form-step-2-container" class="form-step-container d-none">
    <div class="text-center">
        <h2 class="fs-3">Imagens e categoria</h2>
        <p class="text-light">Mostre a todos a logo da sua consultoria e indentifique ela por categorias para facilitar nas buscas </p>
    </div>

    <div class="mt-3">
        <div class="mb-4">
            <h5>Imagens</h5>
            <div class="form-text text-subtitle">
                <p>Dica: Deixe a logo da sua consultoria como primeira imagem. Nas demais você pode colocar fotos do time ou resultados de alunos</p>
                <p>Máximo de 5 imagens</p>
            </div>

            <div class="images">
                <input type="file" name="consulting_images[]" id="consulting_images" class="consulting_images" multiple>
                <label for="consulting_images" class="btn btn-primary"><i class="fas fa-plus"></i> Escolher imagens</label>
                <button type="button" class="btn btn-danger" id="clean_images_btn"><i class="fas fa-trash"></i> Limpar imagens</button>

                <div id="images_preview"></div>
                <?php if($this->view->type == "edit") { ?>
                    <h6>Imagens atuais da consultoria</h6>
                    <div class="old_images">
                        <?php foreach ($this->view->consulting_form->consulting_images as $image) { ?>
                            <div class="old_image">
                                <div class="trash_checkbox">
                                    <label for="delete_images_<?= $image->consulting_image_id ?>"><i class="fas fa-trash "></i></label>
                                    <input type="checkbox" name="delete_images[]" id="delete_images_<?= $image->consulting_image_id ?>" value="<?= $image->consulting_image_id ?>">
                                </div>
                                <img src="<?= '/image_uploads/' . $image->db_saved_name ?>">
                            </div>
                        <?php } ?>
                    </div>
                <?php } ?>
            </div>
        </div>

        <div class="mb-4">
            <h5>Categorias</h5>
            <div class="form-text text-subtitle">
                Dica: Escolha as categorias que definam seu serviço em específico, de acordo com objetivos e público alvo
            </div>

            <div class="categories">
                <?php foreach ($this->view->categories as $category) { ?>
                    <div class="form-check">
                        <input class="form-check-input" 
                               type="checkbox" 
                               id="categories_<?= $category['category_id'] ?>" 
                               name="categories[]" 
                               value="<?= $category['category_id'] ?>"
                               <?= in_array($category['category_id'], $this->view->consulting_form->categories) ? "checked" : "" ?>
                        >
                        <label class="form-check-label" for="categories_<?= $category['category_id'] ?>"><?= $category['category_name'] ?></label>
                    </div>
                <?php } ?>
            </div>
        </div>
    </div>
</fieldset>