<form action="#" class="mt-3">
    <div class="mb-4">
        <label for="name" class="form-label">Nome da consultoria *</label>
        <input type="text" class="form-control" id="name" aria-describedby="name">
        <div id="emailHelp" class="form-text text-subtitle">Nome da marca pela qual as pessoas te reconhecem</div>
    </div>

    <div class="mb-4">
        <label for="contact_email" class="form-label">Email de contato *</label>
        <input type="email" class="form-control" id="contact_email" aria-describedby="contact_email">
    </div>

    <div class="mb-4">
        <label for="contact_phone" class="form-label">Telefone de contato</label>
        <input type="email" class="form-control" id="contact_phone" aria-describedby="contact_phone">
    </div>

    <div class="mb-4">
        <label for="desc" class="form-label">Descrição</label>
        <textarea class="form-control" placeholder="Explique brevemente como funciona sua consultoria" id="desc"></textarea>
    </div>

    <div class="form_actions mt-5">
        <button type="submit" class="btn btn-primary">Salvar e continuar</button>
    </div>
</form>