<fieldset id="form-step-4-container" class="form-step-container d-none">
    <div class="text-center">
        <h2 class="fs-3">Profissionais atuantes</h2>
        <p class="text-light">Registre os profissionais que trabalham com você </p>
    </div>

    <div class="mt-3">
        <input type="hidden" name="form_step" value="3">

        <div id="professionals">
        </div>

        <button type="button" class="btn btn-success" id="add_professional">
            <i class="fas fa-user-plus"></i> Adicionar profissional
        </button>
    </div>
</fieldset>