<div class="container mt-5">
    <div class="row">

    <form class="col-md-6 needs-validation form-forgot" novalidate>
        <span class="over-flow-atras d-block d-md-inline d-none ">ESQUECI SENHA</span>
        
        <div class="row">
          <div class="col">
            <h1 class="mb-5"><strong>Esqueci a Senha</strong></h1>
          </div>
          <div class="col-auto ml-auto">
            <a href="/landing_page" style="color:var(--white-color)"><i class="fas fa-home"></i></a> 
          </div>
        </div>

        <div class="col d-md-block">
            <p>Esqueceu sua senha? Não se preocupe, estamos aqui para ajudar.</p>
            <p>Por favor, insira seu endereço de e-mail abaixo e nós enviaremos instruções para redefinir sua senha.</p>
        </div>

        <div class="form-row">
            <div class="form-group mb-3">
                <label for="email" class="email">E-mail :</label>
                <input type="email" class="form-control" id="email" autocomplete="email" required>
            </div>
            
            <button type="submit" class="btn btn-primary btn-block mb-3"><a href="/forgotPassword/new">Enviar</a></button>
        </div>

        <div class="link">
            <p>Lembrou da Senha? <a href="/sign_in" class="linkSignUp">Faça o Login</a></p>
        </div>
    
    </form>

    <div class="col d-none d-md-block">
        <img src="/assets/img/interrogacao.png" alt="Imagem" class="img-fluid " >
    </div>
    
  </div>

</div>


<script src="/assets/javascripts/formValidation.js" defer></script>

