<div class="container mt-5">
    <div class="row">

    <form class="col-md-6 needs-validation form-forgot" novalidate>
        <span class="over-flow-atras">ESQUECI SENHA</span>
        <h1 class="mb-5"><strong>Esqueci a Senha</strong></h1>

        <div class="col d-none d-md-block">
            <p>Esqueceu sua senha? Não se preocupe, estamos aqui para ajudar.</p>
            <p>Por favor, insira seu endereço de e-mail abaixo e nós enviaremos instruções para redefinir sua senha.</p>
        </div>

        <div class="form-row">
            <div class="form-group mb-3">
                <label for="email" class="email">E-mail :</label>
                <input type="email" class="form-control" id="email" autocomplete="email" required>
            </div>
            
            <button type="submit" class="btn btn-primary btn-block mb-3">Enviar</button>
        </div>

        <div class="link">
            <p>Lembrou da Senha? <a href="/sign_in" class="linkSignUp">  Faça o Login </a></p>
        </div>
    
    </form>

    <div class="col d-none d-md-block">
        <img src="/assets/img/interrogacao.png" alt="Imagem" class="img-fluid " >
    </div>
    
  </div>

</div>


<script src="/assets/javascripts/formValidation.js" defer></script>

