<div class="floating-btn-container d-lg-none">
    <button type="btn" id="toggle-steps-show"><i class="fas fa-chevron-circle-right" id="toggle-steps-icon"></i></button>
</div>

<div class="container mt-5">
    <?php if(count($this->view->consulting_form->get_errors()) > 0){ ?>
        <div class="alert alert-danger alert-dismissible fade show errors_alert" role="alert">
            <strong><i class="fa-solid fa-circle-exclamation"></i> Corrija os seguintes erros:</strong>
            <ul>
                <?php foreach($this->view->consulting_form->get_errors() as $error) { ?>
                    <li><?= $error ?></li>
                <?php } ?>
            </ul>
            <small>Faça upload das imagens de novo</small>

            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    <?php } ?>

    <div class="row">
        <div class="col-lg-4 d-none d-lg-block" id="steps-show-column">
            <div class="bg-opacity-50 rounded py-4 px-3 bg-for-cell steps-show-column">
                <h1 class="fs-2"><?= $this->view->action ?> consultoria</h1>
                <p class="text-light">Crie e configure sua consultoria nos seguintes passos:</p>
                <hr>
                <div id="steps">
                    <div class="step-container">
                        <div class="step mb-3">
                            <div class="row">
                                <div class="col-8 step-info">
                                    <h3 class="fs-5">Informações básicas</h3>
                                    <small class="text-subtitle">
                                        Informações de identificação e contato com a consultoria
                                    </small>
                                </div>
                                <div class="col-4 d-flex justify-content-center align-items-center">
                                    <div class="step-circle" id="step-1-circle">
                                        <i class="fas fa-info"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="step-container">
                        <div class="step mb-3">
                            <div class="row">
                                <div class="col-8 step-info">
                                    <h3 class="fs-5">Imagens e categoria</h3>
                                    <small class="text-subtitle">
                                        Mostre a todos a logo da sua consultoria e indentifique ela por categorias para facilitar nas buscas
                                    </small>
                                </div>
                                <div class="col-4 d-flex justify-content-center align-items-center">
                                    <div class="step-circle" id="step-2-circle">
                                        <i class="fas fa-images"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="step-container">
                        <div class="step mb-3">
                            <div class="row">
                                <div class="col-8 step-info">
                                    <h3 class="fs-5">Benefícios</h3>
                                    <small class="text-subtitle">O que sua consultoria oferece ao cliente?</small>
                                </div>
                                <div class="col-4 d-flex justify-content-center align-items-center">
                                    <div class="step-circle" id="step-3-circle">
                                        <i class="fas fa-dumbbell"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="step-container">
                        <div class="step mb-3">
                            <div class="row">
                                <div class="col-8 step-info">
                                    <h3 class="fs-5">Profissionais atuantes</h3>
                                    <small class="text-subtitle">Registre os profissionais que trabalham com você</small>
                                </div>
                                <div class="col-4 d-flex justify-content-center align-items-center">
                                    <div class="step-circle" id="step-4-circle">
                                        <i class="fas fa-users"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="step-container">
                        <div class="step">
                            <div class="row">
                                <div class="col-8 step-info">
                                    <h3 class="fs-5">Planos e preços</h3>
                                    <small class="text-subtitle">Planos, benefícios incluídos e mensalidade</small>
                                </div>
                                <div class="col-4 d-flex justify-content-center align-items-center">
                                    <div class="step-circle" id="step-5-circle">
                                        <i class="fas fa-dollar-sign"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-7 ms-lg-5">
            <form action="<?= $this->view->form_action ?>" method="post" id="consulting_form" class="mt-3" enctype='multipart/form-data' novalidate>
                <?php require 'partials/form_step_1.phtml' ?>
                <?php require 'partials/form_step_2.phtml' ?>
                <?php require 'partials/form_step_3.phtml' ?>
                <?php require 'partials/form_step_4.phtml' ?>
                <?php require 'partials/form_step_5.phtml' ?>

                <div class="form_actions mt-3">
                    <button type="button" class="btn btn-secondary d-none" id="previous-step">Voltar</button>
                    <button type="button" class="btn btn-primary" id="next-step">Prosseguir</button>
                    <button type="submit" class="btn btn-success d-none" id="submit-consulting">Criar consultoria</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal fade modal-lg" tabindex="-1" id="consulting_form_confirm_modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Confirme as informações da sua consultoria</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
        <div class="modal-body">
            <p><i class="fa-solid fa-circle-exclamation"></i> Você está prestes a criar uma nova consultoria e publicá-la na Spotfit</p>
            <p>Verifique se todas as informações estão corretas passando pelo formulário novamente</p>
            <small>
                Dica: Use os botões
                <button type="button" class="btn btn-secondary btn-sm">Voltar</button>
                <button type="button" class="btn btn-primary btn-sm">Prosseguir</button>
            </small>
        </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-success" id="true_submit_form_btn"><i class="fas fa-check"></i> Confirmar e salvar</button>
            </div>
        </div>
    </div>
</div>

<script src="/assets/javascripts/new_consulting_form/toggle_step_btn.js"></script>
<script src="/assets/javascripts/new_consulting_form/control_form_step.js"></script>
<script src="/assets/javascripts/new_consulting_form/step_2.js"></script>
<script src="/assets/javascripts/new_consulting_form/step_3.js"></script>
<script src="/assets/javascripts/new_consulting_form/step_4.js"></script>
<script src="/assets/javascripts/new_consulting_form/step_5.js"></script>