<?php 

$parametros = $this->view->parametros;
?>

<?php if(isset($_GET['created_msg']) && $_GET['created_msg'] == "1"){ ?>
    <div class="container">
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <p><strong>Consultoria salva com sucesso!</strong></p>
            <p>Agora é só aguardar nosso time analizar sua consultoria para disponibilizá-la para o público</p>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    </div>
<?php } ?>

<section id="fpTitleSection">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h1 class="spot-h1">
                    Encontre o seu profissional
                </h1>
            </div>
        </div>

        <hr>

        <div class="row search-filters-container">
            <form method="GET" style="display:flex" id="filterForm">
                <div class="col-12 col-md-2">
                    <div class="form-floating spot-bt-selector">
                        <select name="sort" class="form-select" onchange="document.getElementById('filterForm').submit();">
                            <option value="1" <?= isset($_GET['sort']) && $_GET['sort'] == '1' ? 'selected' : '' ?>>Mais Cutidas</option>
                            <option value="2" <?= isset($_GET['sort']) && $_GET['sort'] == '2' ? 'selected' : '' ?>>Mais Vistas</option>
                            <option value="3" <?= isset($_GET['sort']) && $_GET['sort'] == '3' ? 'selected' : '' ?>>Mais Novas</option>
                        </select>
                    </div>
                </div>
    
                <div class="col-12 col-md-6 ms-auto me-auto">
                    <div class="d-flex fp-search-container">
                        <div class="input-group ">
                            <div action="" method="GET" class="fp-search-fields">
                                <input type="search" name="search" class="form-control" placeholder="O que você procura ?" aria-label="Search" aria-describedby="basic-addon1" value="<?=!empty($_GET['search']) ? $_GET['search'] : '' ?>">
                                <button type="submit" class="input-group-text" id="basic-addon1">
                                    <i class="fas fa-search"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <hr>
    </div>
</section>

<section id="fpListingProfessionalsSection">
    
    <div class="container">
        <div class="row">
    <?php
    foreach ($parametros as $record) {
    ?>
        <div class="card fp-professional-card--container">
            <a href="/consulting?prof=<?= $record['consulting_id']; ?>">
                <label for="" class="fp-professional-card--label-categorie"><?= $record['category_name']; ?></label>
                <img src="image_uploads/<?= $record['image_dir']; ?>" class="card-img-top" alt="<?= $record['description']; ?>">
                <div class="card-body">
                    <div class="fp-professional-card--content">
                        <h5 class="fp-professional-card--title"><?= $record['consulting_name']; ?></h5>
                        <label class="fp-professional-card--label-new">NOVO</label>
                        <p class="fp-professional-card--text"><?= $record['name']; ?></p>
                    </div>
                    <!-- <hr>
                    <div class="fp-professional-card--heart-container">
                        <img src="assets/icons/solar_heart-broken.svg" alt="">
                        <p class="fp-professional-card--heart-count">Saúde</p>
                    </div> -->
                </div>
            </a>
        </div>
        <?php
    } ?>
    </div>
    </div>

</section>