<?php 

$parametros = $this->view->parametros;
?>

<section id="fpTitleSection">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h1 class="spot-h1">
                    Encontre o seu profissional
                </h1>
            </div>
        </div>

        <hr>

        <div class="row search-filters-container">
            <div class="col-12 col-md-2">
                <div class="form-floating spot-bt-selector">
                    <select class="form-select">
                        <option value="1" selected>Mais Novo</option>
                        <option value="2">Mais Antigo</option>
                    </select>
                </div>
            </div>

            <div class="col-12 col-md-6 ms-auto me-auto">
                <form class="d-flex fp-search-container">
                    <div class="input-group ">
                        <form action="" method="GET">
                            <input type="search" name="search" class="form-control" placeholder="O que você procura ?" aria-label="Search" aria-describedby="basic-addon1" value="<?=!empty($_GET['search']) ? $_GET['search'] : '' ?>">
                            <button type="submit" class="input-group-text" id="basic-addon1">
                                <i class="fas fa-search"></i>
                            </button>
                        </form>
                    </div>
                </form>
            </div>
        </div>
        <hr>
    </div>
</section>

<section id="fpListingProfessionalsSection">
    
    <div class="container">
        <div class="row">
    <?php
    foreach ($parametros as $record) {
    ?>
        <div class="card fp-professional-card--container">
            <a href="/consulting?prof=<?= $record['consulting_id']; ?>">
                <label for="" class="fp-professional-card--label-categorie"><?= $record['category_name']; ?></label>
                <img src="<?= $record['image_dir']; ?>" class="card-img-top" alt="<?= $record['description']; ?>">
                <div class="card-body">
                    <div class="fp-professional-card--content">
                        <h5 class="fp-professional-card--title"><?= $record['consulting_name']; ?></h5>
                        <label class="fp-professional-card--label-new">NOVO</label>
                        <p class="fp-professional-card--text"><?= $record['name']; ?></p>
                    </div>
                    <hr>
                    <div class="fp-professional-card--heart-container">
                        <img src="assets/icons/solar_heart-broken.svg" alt="">
                        <p class="fp-professional-card--heart-count">Saúde</p>
                    </div>
                </div>
            </a>
        </div>
        <?php
    } ?>
    </div>
    </div>

</section>