<section id="fpTitleSection">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h1 class="spot-h1">
                    Encontre o seu profissional
                </h1>
            </div>
        </div>

        <hr>

        <div class="row search-filters-container">
            <div class="col-12 col-md-2">
                <div class="form-floating spot-bt-selector">
                    <select class="form-select">
                        <option value="1" selected>Mais Novo</option>
                        <option value="2">Mais Antigo</option>
                    </select>
                </div>
            </div>

            <div class="col-12 col-md-6 ms-auto me-auto">
                <form class="d-flex fp-search-container">
                    <div class="input-group ">
                        <form action="" method="GET">
                            <input type="search" name="search" class="form-control" placeholder="O que você procura ?" aria-label="Search" aria-describedby="basic-addon1" value="<?=!empty($_GET['search']) ? $_GET['search'] : '' ?>">
                            <button type="submit" class="input-group-text" id="basic-addon1">
                                <i class="fas fa-search"></i>
                            </button>
                        </form>
                    </div>
                </form>
            </div>
        </div>
        <hr>
    </div>
</section>

<section id="fpListingProfessionalsSection">
    
    <div class="container">
        <div class="row">
            <div class="card fp-professional-card--container">
                <a href="/consulting?prof=234">
                    <label for="" class="fp-professional-card--label-categorie">Nutrição</label>
                    <img src="/assets/img/models/nutricionista2.jpg" class="card-img-top" alt="...">
                    <div class="card-body">
                        <div class="fp-professional-card--content">
                            <h5 class="fp-professional-card--title">Clinica Nutri SBC</h5>
                            <label class="fp-professional-card--label-new">NOVO</label>
                            <p class="fp-professional-card--text">Dra. Janaina.</p>
                        </div>
                        <hr>
                        <div class="fp-professional-card--heart-container">
                            <img src="assets/icons/solar_heart-broken.svg" alt="">
                            <p class="fp-professional-card--heart-count">98</label>
                        </div>
                    </div>
                </a>
            </div>
            <div class="card fp-professional-card--container">
                <a href="#">
                    <label for="" class="fp-professional-card--label-categorie">Fisioterapia</label>
                    <img src="/assets/img/models/fisioterapeuta.jpeg" class="card-img-top" alt="...">
                    <div class="card-body">
                        <div class="fp-professional-card--content">
                            <h5 class="fp-professional-card--title">Unidade de Fisioterapia Paulista</h5>
                            <label class="fp-professional-card--label-new">NOVO</label>
                            <p class="fp-professional-card--text">Dr. Paulo.</p>
                        </div>
                        <hr>
                        <div class="fp-professional-card--heart-container">
                            <img src="assets/icons/solar_heart-broken.svg" alt="">
                            <p class="fp-professional-card--heart-count">71</label>
                        </div>
                    </div>
                </a>
            </div>
            <div class="card fp-professional-card--container">
                <a href="#">
                    <label for="" class="fp-professional-card--label-categorie">Nutrição</label>
                    <img src="/assets/img/models/nutricionista.png" class="card-img-top" alt="...">
                    <div class="card-body">
                        <div class="fp-professional-card--content">
                            <h5 class="fp-professional-card--title">Clinica Nutrição SBC</h5>
                            <label class="fp-professional-card--label-new">NOVO</label>
                            <p class="fp-professional-card--text">Dra. Patrícia</p>
                        </div>
                        <hr>
                        <div class="fp-professional-card--heart-container">
                            <img src="assets/icons/solar_heart-broken.svg" alt="">
                            <p class="fp-professional-card--heart-count">45</label>
                        </div>
                    </div>
                </a>
            </div>
            <div class="card fp-professional-card--container">
                <a href="#">
                    <label for="" class="fp-professional-card--label-categorie">Psicologia</label>
                    <img src="/assets/img/models/fisioterapeuta.jpeg" class="card-img-top" alt="...">
                    <div class="card-body">
                        <div class="fp-professional-card--content">
                            <h5 class="fp-professional-card--title">Clinica Terapeutica Berrini</h5>
                            <label class="fp-professional-card--label-new">NOVO</label>
                            <p class="fp-professional-card--text">Dra. Ângela</p>
                        </div>
                        <hr>
                        <div class="fp-professional-card--heart-container">
                            <img src="assets/icons/solar_heart-broken.svg" alt="">
                            <p class="fp-professional-card--heart-count">78</label>
                        </div>
                    </div>
                </a>
            </div>
            <div class="card fp-professional-card--container">
                <a href="#">
                    <label for="" class="fp-professional-card--label-categorie">Fisioterapia</label>
                    <img src="/assets/img/models/fisioterapeuta3.png" class="card-img-top" alt="...">
                    <div class="card-body">
                        <div class="fp-professional-card--content">
                            <h5 class="fp-professional-card--title">Centro Fisioterapia Cohan</h5>
                            <label class="fp-professional-card--label-new">NOVO</label>
                            <p class="fp-professional-card--text">Dra. Ágata</p>
                        </div>
                        <hr>
                        <div class="fp-professional-card--heart-container">
                            <img src="assets/icons/solar_heart-broken.svg" alt="">
                            <p class="fp-professional-card--heart-count">7</label>
                        </div>
                    </div>
                </a>
            </div>
            <div class="card fp-professional-card--container">
                <a href="#">
                    <label for="" class="fp-professional-card--label-categorie">Fitness</label>
                    <img src="/assets/img/models/m1.png" class="card-img-top" alt="...">
                    <div class="card-body">
                        <div class="fp-professional-card--content">
                            <h5 class="fp-professional-card--title">Centro Fitness SCS</h5>
                            <label class="fp-professional-card--label-new">NOVO</label>
                            <p class="fp-professional-card--text">Mestre Pablo.</p>
                        </div>
                        <hr>
                        <div class="fp-professional-card--heart-container">
                            <img src="assets/icons/solar_heart-broken.svg" alt="">
                            <p class="fp-professional-card--heart-count">7</label>
                        </div>
                    </div>
                </a>
            </div>
            <div class="card fp-professional-card--container">
                <a href="#">
                    <label for="" class="fp-professional-card--label-categorie">Fitness</label>
                    <img src="/assets/img/models/m1.png" class="card-img-top" alt="...">
                    <div class="card-body">
                        <div class="fp-professional-card--content">
                            <h5 class="fp-professional-card--title">Centro Fitness SCS</h5>
                            <label class="fp-professional-card--label-new">NOVO</label>
                            <p class="fp-professional-card--text">Mestre Pablo.</p>
                        </div>
                        <hr>
                        <div class="fp-professional-card--heart-container">
                            <img src="assets/icons/solar_heart-broken.svg" alt="">
                            <p class="fp-professional-card--heart-count">7</label>
                        </div>
                    </div>
                </a>
            </div>
            <div class="card fp-professional-card--container">
                <a href="#">
                    <label for="" class="fp-professional-card--label-categorie">Fitness</label>
                    <img src="/assets/img/models/m1.png" class="card-img-top" alt="...">
                    <div class="card-body">
                        <div class="fp-professional-card--content">
                            <h5 class="fp-professional-card--title">Centro Fitness SCS</h5>
                            <label class="fp-professional-card--label-new">NOVO</label>
                            <p class="fp-professional-card--text">Mestre Pablo.</p>
                        </div>
                        <hr>
                        <div class="fp-professional-card--heart-container">
                            <img src="assets/icons/solar_heart-broken.svg" alt="">
                            <p class="fp-professional-card--heart-count">7</label>
                        </div>
                    </div>
                </a>
            </div>
            <div class="card fp-professional-card--container">
                <a href="#">
                    <label for="" class="fp-professional-card--label-categorie">Fitness</label>
                    <img src="/assets/img/models/m1.png" class="card-img-top" alt="...">
                    <div class="card-body">
                        <div class="fp-professional-card--content">
                            <h5 class="fp-professional-card--title">Centro Fitness SCS</h5>
                            <label class="fp-professional-card--label-new">NOVO</label>
                            <p class="fp-professional-card--text">Mestre Pablo.</p>
                        </div>
                        <hr>
                        <div class="fp-professional-card--heart-container">
                            <img src="assets/icons/solar_heart-broken.svg" alt="">
                            <p class="fp-professional-card--heart-count">7</label>
                        </div>
                    </div>
                </a>
            </div>
            <div class="card fp-professional-card--container">
                <a href="#">
                    <label for="" class="fp-professional-card--label-categorie">Fitness</label>
                    <img src="/assets/img/models/m1.png" class="card-img-top" alt="...">
                    <div class="card-body">
                        <div class="fp-professional-card--content">
                            <h5 class="fp-professional-card--title">Centro Fitness SCS</h5>
                            <label class="fp-professional-card--label-new">NOVO</label>
                            <p class="fp-professional-card--text">Mestre Pablo.</p>
                        </div>
                        <hr>
                        <div class="fp-professional-card--heart-container">
                            <img src="assets/icons/solar_heart-broken.svg" alt="">
                            <p class="fp-professional-card--heart-count">7</label>
                        </div>
                    </div>
                </a>
            </div>
            <div class="card fp-professional-card--container">
                <a href="#">
                    <label for="" class="fp-professional-card--label-categorie">Fitness</label>
                    <img src="/assets/img/models/m1.png" class="card-img-top" alt="...">
                    <div class="card-body">
                        <div class="fp-professional-card--content">
                            <h5 class="fp-professional-card--title">Centro Fitness SCS</h5>
                            <label class="fp-professional-card--label-new">NOVO</label>
                            <p class="fp-professional-card--text">Mestre Pablo.</p>
                        </div>
                        <hr>
                        <div class="fp-professional-card--heart-container">
                            <img src="assets/icons/solar_heart-broken.svg" alt="">
                            <p class="fp-professional-card--heart-count">7</label>
                        </div>
                    </div>
                </a>
            </div>
            <div class="card fp-professional-card--container">
                <a href="#">
                    <label for="" class="fp-professional-card--label-categorie">Fitness</label>
                    <img src="/assets/img/models/m1.png" class="card-img-top" alt="...">
                    <div class="card-body">
                        <div class="fp-professional-card--content">
                            <h5 class="fp-professional-card--title">Centro Fitness SCS</h5>
                            <label class="fp-professional-card--label-new">NOVO</label>
                            <p class="fp-professional-card--text">Mestre Pablo.</p>
                        </div>
                        <hr>
                        <div class="fp-professional-card--heart-container">
                            <img src="assets/icons/solar_heart-broken.svg" alt="">
                            <p class="fp-professional-card--heart-count">7</label>
                        </div>
                    </div>
                </a>
            </div>
            <div class="card fp-professional-card--container">
                <a href="#">
                    <label for="" class="fp-professional-card--label-categorie">Fitness</label>
                    <img src="/assets/img/models/m1.png" class="card-img-top" alt="...">
                    <div class="card-body">
                        <div class="fp-professional-card--content">
                            <h5 class="fp-professional-card--title">Centro Fitness SCS</h5>
                            <label class="fp-professional-card--label-new">NOVO</label>
                            <p class="fp-professional-card--text">Mestre Pablo.</p>
                        </div>
                        <hr>
                        <div class="fp-professional-card--heart-container">
                            <img src="assets/icons/solar_heart-broken.svg" alt="">
                            <p class="fp-professional-card--heart-count">7</label>
                        </div>
                    </div>
                </a>
            </div>
            <div class="card fp-professional-card--container">
                <a href="#">
                    <label for="" class="fp-professional-card--label-categorie">Fitness</label>
                    <img src="/assets/img/models/m1.png" class="card-img-top" alt="...">
                    <div class="card-body">
                        <div class="fp-professional-card--content">
                            <h5 class="fp-professional-card--title">Centro Fitness SCS</h5>
                            <label class="fp-professional-card--label-new">NOVO</label>
                            <p class="fp-professional-card--text">Mestre Pablo.</p>
                        </div>
                        <hr>
                        <div class="fp-professional-card--heart-container">
                            <img src="assets/icons/solar_heart-broken.svg" alt="">
                            <p class="fp-professional-card--heart-count">7</label>
                        </div>
                    </div>
                </a>
            </div>
            <div class="card fp-professional-card--container">
                <a href="#">
                    <label for="" class="fp-professional-card--label-categorie">Fitness</label>
                    <img src="/assets/img/models/m1.png" class="card-img-top" alt="...">
                    <div class="card-body">
                        <div class="fp-professional-card--content">
                            <h5 class="fp-professional-card--title">Centro Fitness SCS</h5>
                            <label class="fp-professional-card--label-new">NOVO</label>
                            <p class="fp-professional-card--text">Mestre Pablo.</p>
                        </div>
                        <hr>
                        <div class="fp-professional-card--heart-container">
                            <img src="assets/icons/solar_heart-broken.svg" alt="">
                            <p class="fp-professional-card--heart-count">7</label>
                        </div>
                    </div>
                </a>
            </div>
            <div class="card fp-professional-card--container">
                <a href="#">
                    <label for="" class="fp-professional-card--label-categorie">Fitness</label>
                    <img src="/assets/img/models/m1.png" class="card-img-top" alt="...">
                    <div class="card-body">
                        <div class="fp-professional-card--content">
                            <h5 class="fp-professional-card--title">Centro Fitness SCS</h5>
                            <label class="fp-professional-card--label-new">NOVO</label>
                            <p class="fp-professional-card--text">Mestre Pablo.</p>
                        </div>
                        <hr>
                        <div class="fp-professional-card--heart-container">
                            <img src="assets/icons/solar_heart-broken.svg" alt="">
                            <p class="fp-professional-card--heart-count">7</label>
                        </div>
                    </div>
                </a>
            </div>
            <div class="card fp-professional-card--container">
                <a href="#">
                    <label for="" class="fp-professional-card--label-categorie">Fitness</label>
                    <img src="/assets/img/models/m1.png" class="card-img-top" alt="...">
                    <div class="card-body">
                        <div class="fp-professional-card--content">
                            <h5 class="fp-professional-card--title">Centro Fitness SCS</h5>
                            <label class="fp-professional-card--label-new">NOVO</label>
                            <p class="fp-professional-card--text">Mestre Pablo.</p>
                        </div>
                        <hr>
                        <div class="fp-professional-card--heart-container">
                            <img src="assets/icons/solar_heart-broken.svg" alt="">
                            <p class="fp-professional-card--heart-count">7</label>
                        </div>
                    </div>
                </a>
            </div>
            <div class="card fp-professional-card--container">
                <a href="#">
                    <label for="" class="fp-professional-card--label-categorie">Fitness</label>
                    <img src="/assets/img/models/m1.png" class="card-img-top" alt="...">
                    <div class="card-body">
                        <div class="fp-professional-card--content">
                            <h5 class="fp-professional-card--title">Centro Fitness SCS</h5>
                            <label class="fp-professional-card--label-new">NOVO</label>
                            <p class="fp-professional-card--text">Mestre Pablo.</p>
                        </div>
                        <hr>
                        <div class="fp-professional-card--heart-container">
                            <img src="assets/icons/solar_heart-broken.svg" alt="">
                            <p class="fp-professional-card--heart-count">7</label>
                        </div>
                    </div>
                </a>
            </div>
            <div class="card fp-professional-card--container">
                <a href="#">
                    <label for="" class="fp-professional-card--label-categorie">Fitness</label>
                    <img src="/assets/img/models/m1.png" class="card-img-top" alt="...">
                    <div class="card-body">
                        <div class="fp-professional-card--content">
                            <h5 class="fp-professional-card--title">Centro Fitness SCS</h5>
                            <label class="fp-professional-card--label-new">NOVO</label>
                            <p class="fp-professional-card--text">Mestre Pablo.</p>
                        </div>
                        <hr>
                        <div class="fp-professional-card--heart-container">
                            <img src="assets/icons/solar_heart-broken.svg" alt="">
                            <p class="fp-professional-card--heart-count">7</label>
                        </div>
                    </div>
                </a>
            </div>
            <div class="card fp-professional-card--container">
                <a href="#">
                    <label for="" class="fp-professional-card--label-categorie">Fitness</label>
                    <img src="/assets/img/models/m1.png" class="card-img-top" alt="...">
                    <div class="card-body">
                        <div class="fp-professional-card--content">
                            <h5 class="fp-professional-card--title">Centro Fitness SCS</h5>
                            <label class="fp-professional-card--label-new">NOVO</label>
                            <p class="fp-professional-card--text">Mestre Pablo.</p>
                        </div>
                        <hr>
                        <div class="fp-professional-card--heart-container">
                            <img src="assets/icons/solar_heart-broken.svg" alt="">
                            <p class="fp-professional-card--heart-count">7</label>
                        </div>
                    </div>
                </a>
            </div>
            <div class="card fp-professional-card--container">
                <a href="#">
                    <label for="" class="fp-professional-card--label-categorie">Fitness</label>
                    <img src="/assets/img/models/m1.png" class="card-img-top" alt="...">
                    <div class="card-body">
                        <div class="fp-professional-card--content">
                            <h5 class="fp-professional-card--title">Centro Fitness SCS</h5>
                            <label class="fp-professional-card--label-new">NOVO</label>
                            <p class="fp-professional-card--text">Mestre Pablo.</p>
                        </div>
                        <hr>
                        <div class="fp-professional-card--heart-container">
                            <img src="assets/icons/solar_heart-broken.svg" alt="">
                            <p class="fp-professional-card--heart-count">7</label>
                        </div>
                    </div>
                </a>
            </div>
            <div class="card fp-professional-card--container">
                <a href="#">
                    <label for="" class="fp-professional-card--label-categorie">Fitness</label>
                    <img src="/assets/img/models/m1.png" class="card-img-top" alt="...">
                    <div class="card-body">
                        <div class="fp-professional-card--content">
                            <h5 class="fp-professional-card--title">Centro Fitness SCS</h5>
                            <label class="fp-professional-card--label-new">NOVO</label>
                            <p class="fp-professional-card--text">Mestre Pablo.</p>
                        </div>
                        <hr>
                        <div class="fp-professional-card--heart-container">
                            <img src="assets/icons/solar_heart-broken.svg" alt="">
                            <p class="fp-professional-card--heart-count">7</label>
                        </div>
                    </div>
                </a>
            </div>
            <div class="card fp-professional-card--container">
                <a href="#">
                    <label for="" class="fp-professional-card--label-categorie">Fitness</label>
                    <img src="/assets/img/models/m1.png" class="card-img-top" alt="...">
                    <div class="card-body">
                        <div class="fp-professional-card--content">
                            <h5 class="fp-professional-card--title">Centro Fitness SCS</h5>
                            <label class="fp-professional-card--label-new">NOVO</label>
                            <p class="fp-professional-card--text">Mestre Pablo.</p>
                        </div>
                        <hr>
                        <div class="fp-professional-card--heart-container">
                            <img src="assets/icons/solar_heart-broken.svg" alt="">
                            <p class="fp-professional-card--heart-count">7</label>
                        </div>
                    </div>
                </a>
            </div>
            <div class="card fp-professional-card--container">
                <a href="#">
                    <label for="" class="fp-professional-card--label-categorie">Fitness</label>
                    <img src="/assets/img/models/m1.png" class="card-img-top" alt="...">
                    <div class="card-body">
                        <div class="fp-professional-card--content">
                            <h5 class="fp-professional-card--title">Centro Fitness SCS</h5>
                            <label class="fp-professional-card--label-new">NOVO</label>
                            <p class="fp-professional-card--text">Mestre Pablo.</p>
                        </div>
                        <hr>
                        <div class="fp-professional-card--heart-container">
                            <img src="assets/icons/solar_heart-broken.svg" alt="">
                            <p class="fp-professional-card--heart-count">7</label>
                        </div>
                    </div>
                </a>
            </div>
            <div class="card fp-professional-card--container">
                <a href="#">
                    <label for="" class="fp-professional-card--label-categorie">Fitness</label>
                    <img src="/assets/img/models/m1.png" class="card-img-top" alt="...">
                    <div class="card-body">
                        <div class="fp-professional-card--content">
                            <h5 class="fp-professional-card--title">Centro Fitness SCS</h5>
                            <label class="fp-professional-card--label-new">NOVO</label>
                            <p class="fp-professional-card--text">Mestre Pablo.</p>
                        </div>
                        <hr>
                        <div class="fp-professional-card--heart-container">
                            <img src="assets/icons/solar_heart-broken.svg" alt="">
                            <p class="fp-professional-card--heart-count">7</label>
                        </div>
                    </div>
                </a>
            </div>
            <div class="card fp-professional-card--container">
                <a href="#">
                    <label for="" class="fp-professional-card--label-categorie">Fitness</label>
                    <img src="/assets/img/models/m1.png" class="card-img-top" alt="...">
                    <div class="card-body">
                        <div class="fp-professional-card--content">
                            <h5 class="fp-professional-card--title">Centro Fitness SCS</h5>
                            <label class="fp-professional-card--label-new">NOVO</label>
                            <p class="fp-professional-card--text">Mestre Pablo.</p>
                        </div>
                        <hr>
                        <div class="fp-professional-card--heart-container">
                            <img src="assets/icons/solar_heart-broken.svg" alt="">
                            <p class="fp-professional-card--heart-count">7</label>
                        </div>
                    </div>
                </a>
            </div>
            <div class="card fp-professional-card--container">
                <a href="#">
                    <label for="" class="fp-professional-card--label-categorie">Fitness</label>
                    <img src="/assets/img/models/m1.png" class="card-img-top" alt="...">
                    <div class="card-body">
                        <div class="fp-professional-card--content">
                            <h5 class="fp-professional-card--title">Centro Fitness SCS</h5>
                            <label class="fp-professional-card--label-new">NOVO</label>
                            <p class="fp-professional-card--text">Mestre Pablo.</p>
                        </div>
                        <hr>
                        <div class="fp-professional-card--heart-container">
                            <img src="assets/icons/solar_heart-broken.svg" alt="">
                            <p class="fp-professional-card--heart-count">7</label>
                        </div>
                    </div>
                </a>
            </div>
            <div class="card fp-professional-card--container">
                <a href="#">
                    <label for="" class="fp-professional-card--label-categorie">Fitness</label>
                    <img src="/assets/img/models/m1.png" class="card-img-top" alt="...">
                    <div class="card-body">
                        <div class="fp-professional-card--content">
                            <h5 class="fp-professional-card--title">Centro Fitness SCS</h5>
                            <label class="fp-professional-card--label-new">NOVO</label>
                            <p class="fp-professional-card--text">Mestre Pablo.</p>
                        </div>
                        <hr>
                        <div class="fp-professional-card--heart-container">
                            <img src="assets/icons/solar_heart-broken.svg" alt="">
                            <p class="fp-professional-card--heart-count">7</label>
                        </div>
                    </div>
                </a>
            </div>
            <div class="card fp-professional-card--container">
                <a href="#">
                    <label for="" class="fp-professional-card--label-categorie">Fitness</label>
                    <img src="/assets/img/models/m1.png" class="card-img-top" alt="...">
                    <div class="card-body">
                        <div class="fp-professional-card--content">
                            <h5 class="fp-professional-card--title">Centro Fitness SCS</h5>
                            <label class="fp-professional-card--label-new">NOVO</label>
                            <p class="fp-professional-card--text">Mestre Pablo.</p>
                        </div>
                        <hr>
                        <div class="fp-professional-card--heart-container">
                            <img src="assets/icons/solar_heart-broken.svg" alt="">
                            <p class="fp-professional-card--heart-count">7</label>
                        </div>
                    </div>
                </a>
            </div>
            <div class="card fp-professional-card--container">
                <a href="#">
                    <label for="" class="fp-professional-card--label-categorie">Fitness</label>
                    <img src="/assets/img/models/m1.png" class="card-img-top" alt="...">
                    <div class="card-body">
                        <div class="fp-professional-card--content">
                            <h5 class="fp-professional-card--title">Centro Fitness SCS</h5>
                            <label class="fp-professional-card--label-new">NOVO</label>
                            <p class="fp-professional-card--text">Mestre Pablo.</p>
                        </div>
                        <hr>
                        <div class="fp-professional-card--heart-container">
                            <img src="assets/icons/solar_heart-broken.svg" alt="">
                            <p class="fp-professional-card--heart-count">7</label>
                        </div>
                    </div>
                </a>
            </div>
            <div class="card fp-professional-card--container">
                <a href="#">
                    <label for="" class="fp-professional-card--label-categorie">Fitness</label>
                    <img src="/assets/img/models/m1.png" class="card-img-top" alt="...">
                    <div class="card-body">
                        <div class="fp-professional-card--content">
                            <h5 class="fp-professional-card--title">Centro Fitness SCS</h5>
                            <label class="fp-professional-card--label-new">NOVO</label>
                            <p class="fp-professional-card--text">Mestre Pablo.</p>
                        </div>
                        <hr>
                        <div class="fp-professional-card--heart-container">
                            <img src="assets/icons/solar_heart-broken.svg" alt="">
                            <p class="fp-professional-card--heart-count">7</label>
                        </div>
                    </div>
                </a>
            </div>
            <div class="card fp-professional-card--container">
                <a href="#">
                    <label for="" class="fp-professional-card--label-categorie">Fitness</label>
                    <img src="/assets/img/models/m1.png" class="card-img-top" alt="...">
                    <div class="card-body">
                        <div class="fp-professional-card--content">
                            <h5 class="fp-professional-card--title">Centro Fitness SCS</h5>
                            <label class="fp-professional-card--label-new">NOVO</label>
                            <p class="fp-professional-card--text">Mestre Pablo.</p>
                        </div>
                        <hr>
                        <div class="fp-professional-card--heart-container">
                            <img src="assets/icons/solar_heart-broken.svg" alt="">
                            <p class="fp-professional-card--heart-count">7</label>
                        </div>
                    </div>
                </a>
            </div>
            <div class="card fp-professional-card--container">
                <a href="#">
                    <label for="" class="fp-professional-card--label-categorie">Fitness</label>
                    <img src="/assets/img/models/m1.png" class="card-img-top" alt="...">
                    <div class="card-body">
                        <div class="fp-professional-card--content">
                            <h5 class="fp-professional-card--title">Centro Fitness SCS</h5>
                            <label class="fp-professional-card--label-new">NOVO</label>
                            <p class="fp-professional-card--text">Mestre Pablo.</p>
                        </div>
                        <hr>
                        <div class="fp-professional-card--heart-container">
                            <img src="assets/icons/solar_heart-broken.svg" alt="">
                            <p class="fp-professional-card--heart-count">7</label>
                        </div>
                    </div>
                </a>
            </div>
        </div>  
    </div>

</section>