<div class="container mt-5">
    <div class="row">
        <div class="col-lg-4 bg-secondary bg-dark bg-gradient bg-opacity-50 rounded py-4 px-3">
            <h1 class="fs-2">Nova consultoria</h1>
            <p class="text-light">Crie e configure sua consultoria nos seguintes passos:</p>
            <hr>
            <div id="steps">
                <div class="step mb-5">
                    <div class="row">
                        <div class="col-8 step-info">
                            <h3 class="fs-5">Informações básicas</h3>
                            <small class="text-subtitle">
                                Informações de identificação e contato com a consultoria
                            </small>
                        </div>
                        <div class="col-4 d-flex justify-content-center align-items-center">
                            <div class="step-circle">
                                <i class="fas fa-info"></i>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="step mb-5">
                    <div class="row">
                        <div class="col-8 step-info">
                            <h3 class="fs-5">Imagens e categoria</h3>
                            <small class="text-subtitle">
                                Mostre a todos a logo da sua consultoria e indentifique ela por categorias para facilitar nas buscas
                            </small>
                        </div>
                        <div class="col-4 d-flex justify-content-center align-items-center">
                            <div class="step-circle">
                                <i class="fas fa-images"></i>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="step mb-5">
                    <div class="row">
                        <div class="col-8 step-info">
                            <h3 class="fs-5">Profissionais atuantes</h3>
                            <small class="text-subtitle">Registre os profissionais que trabalham com você</small>
                        </div>
                        <div class="col-4 d-flex justify-content-center align-items-center">
                            <div class="step-circle">
                                <i class="fas fa-users"></i>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="step mb-5">
                    <div class="row">
                        <div class="col-8 step-info">
                            <h3 class="fs-5">Benefícios</h3>
                            <small class="text-subtitle">O que sua consultoria oferece ao cliente?</small>
                        </div>
                        <div class="col-4 d-flex justify-content-center align-items-center">
                            <div class="step-circle">
                                <i class="fas fa-dumbbell"></i>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="step">
                    <div class="row">
                        <div class="col-8 step-info">
                            <h3 class="fs-5">Planos e preços</h3>
                            <small class="text-subtitle">Planos, benefícios incluídos e mensalidade</small>
                        </div>
                        <div class="col-4 d-flex justify-content-center align-items-center">
                            <div class="step-circle">
                                <i class="fas fa-dollar-sign"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-7 ms-lg-5">
            <?php require 'partials/form_step_' . $_GET['step'] . '.phtml' ?>
        </div>
    </div>
</div>