<section id="ServiceHeadingSection">
    <div class="container">
        <div class="row">
            <div class="col-12 col-lg-8">

                <div class="service-header--container">
                    <div class="service-header--lables-contaiers">
                        <label class="spot-label-orange">FITNESS</label>
                        <label class="spot-label-green">Novo na plataforma</label>
                    </div>
                    <h1 class="service-page--service-title">Centro Fitness SCS</h1>
                </div>

                <div class="professional-service-slider--container">
                    <div class="swiper mySwiper">
                        <div class="swiper-wrapper">
                            <div class="swiper-slide professional-service-slider--item">
                                <img src="/assets/img/models/m1.png" alt="">
                            </div>
                            <div class="swiper-slide professional-service-slider--item">
                                <img src="/assets/img/models/m2.png" alt="">
                            </div>
                            <div class="swiper-slide professional-service-slider--item">
                                <img src="/assets/img/models/m3.png" alt="">
                            </div>
                            <div class="swiper-slide professional-service-slider--item">
                                <img src="/assets/img/models/m2.png" alt="">
                            </div>
                            <div class="swiper-slide professional-service-slider--item">
                                <img src="/assets/img/models/m3.png" alt="">
                            </div>
                        </div>

                        <div class="professional-service-slider--button-next"><i class="fa-solid fa-chevron-right"></i></div>
                        <div class="professional-service-slider--button-prev"><i class="fa-solid fa-chevron-left"></i></div>

                        <div class="professional-service-slider--pagination"></div>
                    </div>

                </div>
            </div>
            <div class="col-12 col-lg-4 professional-service-info--container">
                <div class="professional-service-info--social-media-container">
                    <img src="/assets/icons/share.svg" alt="" class="professional-service-info--social-media-icon">
                    <img src="/assets/icons/solar_heart-broken.svg" alt="" class="professional-service-info--social-media-icon">
                    <img src="/assets/icons/location.svg" alt="" class="professional-service-info--social-media-icon">
                </div>
                
                <div class="professional-service-info--features-container">
                    <div class="professional-service-info--feature-item">
                        <div class="professional-service-feature-item--feature-description">
                            <i class="far fa-heart gray-icon"></i>
                            <p class="professional-service-feature--name">Curtidas</p>
                        </div>

                        <div class="professional-service-feature--intensity-container">
                            <p class="professional-service-feature--intensity-text">
                                87
                            </p>
                        </div>
                    </div>
                    <div class="professional-service-info--feature-item">
                        <div class="professional-service-feature-item--feature-description">
                            <i class="far fa-eye gray-icon"></i>
                            <p class="professional-service-feature--name">Vizualizações</p>
                        </div>

                        <div class="professional-service-feature--intensity-container">
                            <p class="professional-service-feature--intensity-text">
                                500
                            </p>
                        </div>
                    </div>
                    <div class="professional-service-info--feature-item">
                        <div class="professional-service-feature-item--feature-description">
                            <i class="far fa-comments gray-icon"></i>
                            <p class="professional-service-feature--name">Comentários</p>
                        </div>

                        <div class="professional-service-feature--intensity-container">
                            <p class="professional-service-feature--intensity-text">
                                10
                            </p>
                        </div>
                    </div>
                </div>

                <div class="professional-service-info--text-description-container">
                    <p class="professional-service-info--text-description">
                    Um plano de desenvolvimento para atletas de alta performance é essencial para maximizar seu potencial. Com avaliação holística, metas claras, treinamento multidisciplinar. 
                    </p>
                </div>

                <div class="professional-service-info--contact-container">
                    <div class="professional-service-info--contact-item">
                        <i class="fas fa-phone gray-icon"></i>
                        <p class="professional-service-info--contact-text">+55 (11) 98302-0692</p>
                    </div>
                    <div class="professional-service-info--contact-item">
                        <i class="fas fa-envelope gray-icon"></i>
                        <p class="professional-service-info--contact-text">fake.email@gmail.com</p>
                    </div>
                </div>

                <div class="professional-service-info--chat-action-container">
                    <form action="" method="POST">
                        <input type="text" style="display: none" value="<?=!empty($providerId) ? $providerId : ''?>">
                        <button type="submit" class="spot-btn-dark-orange onhover-broom">
                            <span>
                                Entrar em contato pelo Chat
                            </span>
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

<section id="fpDescriptionSection" class="mb-5">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="fp-description-title-area row">
                    <h1 class="spot-text-title">Planos</h1>
                    <p class="spot-text-title-watermark">Planos</p>
                </div>          
            </div>
        </div>

        <div class="row">
            <div class="swiper plans-swiper">
                <div class="swiper-wrapper">
                    <div class="swiper-slide">
                        <div class="card professional-card" style="width: 18rem;">
                            <div class="card-body text-center">
                                <h5 class="card-title">Plano completo semestral</h5>
                                <p class="card-text">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ventore voluptatem ratione</p>
                                <div class="plan-price">
                                    <h6>R$ 600</h6>
                                    <small>/2 meses</small>
                                </div>
                            </div>
                            <h6 class="mt-2 p-1 text-center">Benefícios inclusos</h6>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item"><i class="fas fa-dumbbell"></i> Treino periodizado</li>
                                <li class="list-group-item"><i class="fab fa-apple"></i> Dieta</li>
                                <li class="list-group-item"><i class="fas fa-person"></i> Prescrição de alongamentos</li>
                            </ul>
                        </div>
                    </div>

                    <div class="swiper-slide">
                        <div class="card professional-card" style="width: 18rem;">
                            <div class="card-body text-center">
                                <h5 class="card-title">Plano completo semestral</h5>
                                <p class="card-text">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ventore voluptatem ratione</p>
                                <div class="plan-price">
                                    <h6>R$ 600</h6>
                                    <small>/2 meses</small>
                                </div>
                            </div>
                            <h6 class="mt-2 p-1 text-center">Benefícios inclusos</h6>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item"><i class="fas fa-dumbbell"></i> Treino periodizado</li>
                                <li class="list-group-item"><i class="fab fa-apple"></i> Dieta</li>
                                <li class="list-group-item"><i class="fas fa-person"></i> Prescrição de alongamentos</li>
                            </ul>
                        </div>
                    </div>

                    <div class="swiper-slide">
                        <div class="card professional-card" style="width: 18rem;">
                            <div class="card-body text-center">
                                <h5 class="card-title">Plano completo semestral</h5>
                                <p class="card-text">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ventore voluptatem ratione</p>
                                <div class="plan-price">
                                    <h6>R$ 600</h6>
                                    <small>/2 meses</small>
                                </div>
                            </div>
                            <h6 class="mt-2 p-1 text-center">Benefícios inclusos</h6>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item"><i class="fas fa-dumbbell"></i> Treino periodizado</li>
                                <li class="list-group-item"><i class="fab fa-apple"></i> Dieta</li>
                                <li class="list-group-item"><i class="fas fa-person"></i> Prescrição de alongamentos</li>
                            </ul>
                        </div>
                    </div>

                    <div class="swiper-slide">
                        <div class="card professional-card" style="width: 18rem;">
                            <div class="card-body text-center">
                                <h5 class="card-title">Plano completo semestral</h5>
                                <p class="card-text">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ventore voluptatem ratione</p>
                                <div class="plan-price">
                                    <h6>R$ 600</h6>
                                    <small>/2 meses</small>
                                </div>
                            </div>
                            <h6 class="mt-2 p-1 text-center">Benefícios inclusos</h6>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item"><i class="fas fa-dumbbell"></i> Treino periodizado</li>
                                <li class="list-group-item"><i class="fab fa-apple"></i> Dieta</li>
                                <li class="list-group-item"><i class="fas fa-person"></i> Prescrição de alongamentos</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="lp-control-swiper-categorie-button lp-control-swiper-categorie-button-next"><i class="fa-solid fa-chevron-right"></i></div>
                <div class="lp-control-swiper-categorie-button lp-control-swiper-categorie-button-prev"><i class="fa-solid fa-chevron-left"></i></div>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="fp-description-title-area row">
                    <h1 class="spot-text-title">Nosso time</h1>
                    <p class="spot-text-title-watermark">Nosso time</p>
                </div>          
            </div>
        </div>

        <div class="row">
            <div class="col-3">
                <div class="card">
                    <div class="card-header">Nutricionista</div>
                    <div class="card-body">
                        <h5 class="card-title">Natália Valente</h5>
                        <div class="card-text">
                            <h6>Contato</h6>
                            <div><i class="fab fa-instagram"></i> <a href="">@natalia_valente</a></div>
                            <div><i class="fas fa-envelope"></i> <a href="">natalua.valente@gmail.com</a></div>
                            <div><i class="fab fa-whatsapp"></i> <a href="">11928348392</a></div>
                        </div>
                        <p class="card-text"><small class="text-body-secondary">CFN: 123456</small></p>
                    </div>
                </div>
            </div>

            <div class="col-3">
                <div class="card">
                    <div class="card-header">Nutricionista</div>
                    <div class="card-body">
                        <h5 class="card-title">Natália Valente</h5>
                        <div class="card-text">
                            <h6>Contato</h6>
                            <div><i class="fab fa-instagram"></i> <a href="">@natalia_valente</a></div>
                            <div><i class="fas fa-envelope"></i> <a href="">natalua.valente@gmail.com</a></div>
                            <div><i class="fab fa-whatsapp"></i> <a href="">11928348392</a></div>
                        </div>
                        <p class="card-text"><small class="text-body-secondary">CFN: 123456</small></p>
                    </div>
                </div>
            </div>

            <div class="col-3">
                <div class="card">
                    <div class="card-header">Nutricionista</div>
                    <div class="card-body">
                        <h5 class="card-title">Natália Valente</h5>
                        <div class="card-text">
                            <h6>Contato</h6>
                            <div><i class="fab fa-instagram"></i> <a href="">@natalia_valente</a></div>
                            <div><i class="fas fa-envelope"></i> <a href="">natalua.valente@gmail.com</a></div>
                            <div><i class="fab fa-whatsapp"></i> <a href="">11928348392</a></div>
                        </div>
                        <p class="card-text"><small class="text-body-secondary">CFN: 123456</small></p>
                    </div>
                </div>
            </div>

            <div class="col-3">
                <div class="card">
                    <div class="card-header">Nutricionista</div>
                    <div class="card-body">
                        <h5 class="card-title">Natália Valente</h5>
                        <div class="card-text">
                            <h6>Contato</h6>
                            <div><i class="fab fa-instagram"></i> <a href="">@natalia_valente</a></div>
                            <div><i class="fas fa-envelope"></i> <a href="">natalua.valente@gmail.com</a></div>
                            <div><i class="fab fa-whatsapp"></i> <a href="">11928348392</a></div>
                        </div>
                        <p class="card-text"><small class="text-body-secondary">CFN: 123456</small></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="fp-description-title-area row">
                    <h1 class="spot-text-title">Avaliações</h1>
                    <p class="spot-text-title-watermark">Avaliações</p>
                </div>          
            </div>
        </div>

        <div class="mt-4">
            <h4>Avalie essa consultoria</43>

            <div>
                <i class="fa fa-star checked rating-icon"></i>
                <i class="fa fa-star checked rating-icon"></i>
                <i class="fa fa-star checked rating-icon"></i>
                <i class="fa fa-star checked rating-icon"></i>
                <i class="fa fa-star rating-icon"></i>
            </div>

            <div>
                <textarea class="form-control rating_desc" placeholder="Descreva como foi o atendimento, ou a prescrição de treino e dieta, ou os feedbacks, etc."></textarea>
            </div>
        </div>

        <div class="mt-4">
            <h4>Outras avaliações</43>

            <div class="rated-container mt-3">
                <div class="large-number">4,1</div>
                <div class="stars">
                    <i class="fa fa-star checked rated-icon"></i>
                    <i class="fa fa-star checked rated-icon"></i>
                    <i class="fa fa-star checked rated-icon"></i>
                    <i class="fa fa-star checked rated-icon"></i>
                    <i class="fa fa-star rated-icon"></i>
                </div>
                <small class="qnt-rated">32 avaliações</small>
            </div>

            <div class="user-ratings">
                <div class="user-rating">
                    <div class="user-info">
                        <img src="https://st.depositphotos.com/1144472/2003/i/950/depositphotos_20030237-stock-photo-cheerful-young-man-over-white.jpg" class="user-photo">
                        <span class="user-name">Carlos Lagarto</span>
                        <i class="fas fa-ellipsis-v more-options"></i>
                    </div>
                    <div class="user-stars">
                        <div class="user-star">
                            <i class="fa fa-star checked rated-icon"></i>
                            <i class="fa fa-star checked rated-icon"></i>
                            <i class="fa fa-star checked rated-icon"></i>
                            <i class="fa fa-star checked rated-icon"></i>
                            <i class="fa fa-star rated-icon"></i>
                        </div>

                        <span class="user-rating-date">02/08/2024</span>
                    </div>
                    <div class="user-comment">
                        <span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tenetur sed possimus ad aliquam, quaerat iste enim provident dolorem corporis, quis vero voluptates. Repellendus quam consequatur iure odit laudantium perferendis adipisci!</span>
                    </div>
                </div>

                <div class="user-rating">
                    <div class="user-info">
                        <img src="https://st.depositphotos.com/1144472/2003/i/950/depositphotos_20030237-stock-photo-cheerful-young-man-over-white.jpg" class="user-photo">
                        <span class="user-name">Carlos Lagarto</span>
                        <i class="fas fa-ellipsis-v more-options"></i>
                    </div>
                    <div class="user-stars">
                        <div class="user-star">
                            <i class="fa fa-star checked rated-icon"></i>
                            <i class="fa fa-star checked rated-icon"></i>
                            <i class="fa fa-star checked rated-icon"></i>
                            <i class="fa fa-star checked rated-icon"></i>
                            <i class="fa fa-star rated-icon"></i>
                        </div>

                        <span class="user-rating-date">02/08/2024</span>
                    </div>
                    <div class="user-comment">
                        <span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tenetur sed possimus ad aliquam, quaerat iste enim provident dolorem corporis, quis vero voluptates. Repellendus quam consequatur iure odit laudantium perferendis adipisci!</span>
                    </div>
                </div>

                <div class="user-rating">
                    <div class="user-info">
                        <img src="https://st.depositphotos.com/1144472/2003/i/950/depositphotos_20030237-stock-photo-cheerful-young-man-over-white.jpg" class="user-photo">
                        <span class="user-name">Carlos Lagarto</span>
                        <i class="fas fa-ellipsis-v more-options"></i>
                    </div>
                    <div class="user-stars">
                        <div class="user-star">
                            <i class="fa fa-star checked rated-icon"></i>
                            <i class="fa fa-star checked rated-icon"></i>
                            <i class="fa fa-star checked rated-icon"></i>
                            <i class="fa fa-star checked rated-icon"></i>
                            <i class="fa fa-star rated-icon"></i>
                        </div>

                        <span class="user-rating-date">02/08/2024</span>
                    </div>
                    <div class="user-comment">
                        <span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tenetur sed possimus ad aliquam, quaerat iste enim provident dolorem corporis, quis vero voluptates. Repellendus quam consequatur iure odit laudantium perferendis adipisci!</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<script src="/assets/javascripts/consulting/specificProfessionalPage.js" defer></script>