<?php
// echo "<pre>";
// print_r($this->view->consultingData); die;
$dados = $this->view->consultingData;

if (!empty($_POST["comment_description"]) && !empty($_POST["comment_rating"])) {

    $_POST["comment_description"] = null;
    $_POST["comment_rating"] = null;
}

// print_r($_POST); die;

?>

<section id="ServiceHeadingSection">
    <div class="container">
        <div class="row">
            <div class="col-12 col-lg-8">

                <div class="service-header--container">
                    <div class="service-header--lables-contaiers">
                        <label class="spot-label-orange">FITNESS</label>
                        <label class="spot-label-green">Novo na plataforma</label>
                    </div>
                    <h1 class="service-page--service-title"><?= $dados["consulting"]["consulting_name"]?></h1>
                </div>

                <div class="professional-service-slider--container">
                    <div class="swiper mySwiper">
                        <div class="swiper-wrapper">
                            <?php foreach ($dados['consulting_images'] as $img) { ?>
                                <div class="swiper-slide professional-service-slider--item">
                                    <img src="<?=$img['db_saved_name']?>" alt="">
                                </div>
                            <?php } ?>
                        </div>

                        <div class="professional-service-slider--button-next"><i class="fa-solid fa-chevron-right"></i></div>
                        <div class="professional-service-slider--button-prev"><i class="fa-solid fa-chevron-left"></i></div>

                        <div class="professional-service-slider--pagination"></div>
                    </div>

                </div>
            </div>
            <div class="col-12 col-lg-4 professional-service-info--container">
                <div class="professional-service-info--social-media-container">
                    <img src="/assets/icons/share.svg" alt="Share" class="professional-service-info--social-media-icon" id="shareButton">
                    <form id="likeForm" method="POST" style="display: none;">
                        <input type="hidden" name="like_form" value="1">
                        <input type="hidden" name="user_has_liked" value="<?= $dados['user_has_liked'] ?>">
                        <input type="hidden" name="user_id" value="<?= $_SESSION['user_id'] ?? '' ?>">
                        <input type="hidden" name="consulting_id" value="<?= $_GET['prof'] ?>">
                    </form>

                    <button id="likeButton" onclick="toggleLike()">
                        <?php if ($dados['user_has_liked']) { ?> 
                            <i class="fa-solid fa-heart"></i>
                        <?php } else { ?>
                            <img src="/assets/icons/solar_heart-broken.svg" alt="Like" class="professional-service-info--social-media-icon">
                        <?php } ?>
                    </button>
                    <?php if (!empty($dados["location"])) { ?>
                        <img src="/assets/icons/location.svg" alt="" class="professional-service-info--social-media-icon">
                    <?php } ?>
                </div>
                <div id="copyMessage" style="display:none; padding: 10px 20px; background-color: green; color: white; font-size: 14px; border-radius: 5px; position: fixed; bottom: 20px; left: 50%; transform: translateX(-50%); z-index: 9999;">
                    Link de compartilhamento copiado
                </div>
                
                <div class="professional-service-info--features-container">
                    <div class="professional-service-info--feature-item">
                        <div class="professional-service-feature-item--feature-description">
                            <i class="far fa-heart gray-icon"></i>
                            <p class="professional-service-feature--name">Curtidas</p>
                        </div>

                        <div class="professional-service-feature--intensity-container">
                            <p class="professional-service-feature--intensity-text">
                                <?= $dados["likes_quantity"]["qtd"] ?>
                            </p>
                        </div>
                    </div>
                    <div class="professional-service-info--feature-item">
                        <div class="professional-service-feature-item--feature-description">
                            <i class="far fa-eye gray-icon"></i>
                            <p class="professional-service-feature--name">Vizualizações</p>
                        </div>

                        <div class="professional-service-feature--intensity-container">
                            <p class="professional-service-feature--intensity-text">
                                <?=$dados["totalViews"] ? $dados["totalViews"] : 0 ?>
                            </p>
                        </div>
                    </div>
                    <div class="professional-service-info--feature-item">
                        <div class="professional-service-feature-item--feature-description">
                            <i class="far fa-comments gray-icon"></i>
                            <p class="professional-service-feature--name">Comentários</p>
                        </div>

                        <div class="professional-service-feature--intensity-container">
                            <p class="professional-service-feature--intensity-text">
                                <?= count($dados["comments"]) ?>
                            </p>
                        </div>
                    </div>
                </div>

                <div class="professional-service-info--text-description-container">
                    <p class="professional-service-info--text-description">
                    <?= $dados["consulting"]["description"]?>
                    </p>
                </div>

                <div class="professional-service-info--contact-container">
                    <div class="professional-service-info--contact-item">
                        <i class="fas fa-phone gray-icon"></i>
                        <p class="professional-service-info--contact-text"> <?= $dados["consulting"]["contact_phone"]?></p>
                    </div>
                    <div class="professional-service-info--contact-item">
                        <i class="fas fa-envelope gray-icon"></i>
                        <p class="professional-service-info--contact-text"><?= $dados["consulting"]["contact_email"]?></p>
                    </div>
                </div>

                <div class="professional-service-info--chat-action-container">
                    <?php 
                        $phoneNumber = preg_replace('/\D/', '', $dados["consulting"]["contact_phone"]); // Sanitize phone number
                        $data = preg_replace('/\D/', '', $dados["consulting"]["contact_phone"]) ;
                    ?>

                    <button class="btn btn-outline-light spot-schedule mb-3"
                        id="scheduleContactButton" 
                        title="Agendar um contato para discutir a consultoria">
                        <span>Agendar Contato</span>
                    </button>

                    <!-- Pop-up de Agendamento de Contato -->
                    <div id="scheduleContactModal" class="modal" style="display:none;">
                        <div class="modal-content">
                            <span id="closeModal" class="close">&times;</span>
                            <h3 class="mb-3">Agende um Contato</h3>

                            <form id="contactScheduleForm" method="POST">
                                <div class="mb-3">
                                    <label for="contact_reason" class="form-label">Motivo do contato:</label>
                                    <textarea id="contact_reason" name="contact_reason" class="form-control" required></textarea>
                                </div>
                                <div class="mb-3">
                                    <label for="contact_date" class="form-label">Data e horário preferido:</label>
                                    <input type="datetime-local" id="contact_date" name="contact_date" class="form-control" required />
                                </div>
                                <button type="submit" class="btn btn-primary w-100">Enviar</button>
                            </form>
                        </div>
                    </div>

                    <button href="https://wa.me/<?= $phoneNumber ?>" 
                        target="_blank" class="spot-btn-dark-orange onhover-broom mb-3" 
                        onclick="redirectToWhatsApp(<?=$data ?>)" >
                        <span>Contato pelo WhatsApp</span>
                    </button>
                    
                </div>
            </div>
        </div>
    </div>
</section>

<section id="fpDescriptionSection" class="mb-5">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="fp-description-title-area row">
                    <h1 class="spot-text-title">Planos</h1>
                    <p class="spot-text-title-watermark">Planos</p>
                </div>          
            </div>
        </div>

        <div class="row">
            <div class="swiper plans-swiper">
                <div class="swiper-wrapper">
                    <?php foreach ($dados["plans_benefits"] as $plans) { ?>
                        <div class="swiper-slide">
                            <div class="card professional-card" style="width: 18rem;">
                                <div class="card-body text-center">
                                    <h5 class="card-title"><?=$plans["name"]?></h5>
                                    <p class="card-text"><?=$plans["description"]?></p>
                                    <div class="plan-price">
                                        <h6>R$ <?=$plans["price"]?></h6>
                                        <small>/<?=$plans["period"]?> meses</small>
                                    </div>
                                </div>
                                <h6 class="mt-2 p-1 text-center">Benefícios inclusos</h6>
                                <ul class="list-group list-group-flush">
                                    <?php foreach ($plans["benefits"] as $benefits) {?>
                                        <li class="list-group-item"><?=$benefits["icon"] ? $benefits["icon"] : '<i class="fas fa-person"></i>' ?> <?=$benefits["benefit_name"] ?></li>
                                    <?php } ?>
                                </ul>
                            </div>
                        </div>
                    <?php } ?>
                    
                    <div class="lp-control-swiper-categorie-button lp-control-swiper-categorie-button-next"><i class="fa-solid fa-chevron-right"></i></div>
                    <div class="lp-control-swiper-categorie-button lp-control-swiper-categorie-button-prev"><i class="fa-solid fa-chevron-left"></i></div>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="fp-description-title-area row">
                    <h1 class="spot-text-title">Nosso time</h1>
                    <p class="spot-text-title-watermark">Nosso time</p>
                </div>          
            </div>
        </div>

        <div class="row">
            <?php foreach ($dados["professional_form"] as $professional) { ?>
                <div class="col-3">
                    <div class="card">
                        <div class="card-header"><?=$professional["profession"][0]["profession_name"]?></div>
                        <div class="card-body">
                            <h5 class="card-title"><?=$professional["consulting_professional"]["name"]?></h5>
                            <div class="card-text">
                                <h6>Contato</h6>
                                <div><i class="fab fa-instagram"></i> <a href=""><?=$professional["consulting_professional"]["instagram"]?></a></div>
                                <div><i class="fas fa-envelope"></i> <a href=""><?=$professional["consulting_professional"]["email"]?></a></div>
                                <div><i class="fab fa-whatsapp"></i> <a href=""><?=$professional["consulting_professional"]["phone"]?></a></div>
                            </div>
                            <p class="card-text"><small class="text-body-secondary">CFN: 123456</small></p>
                        </div>
                    </div>
                </div>

            <?php } ?>
    </div>
</section>

<section>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="fp-description-title-area row">
                    <h1 class="spot-text-title">Avaliações</h1>
                    <p class="spot-text-title-watermark">Avaliações</p>
                </div>          
            </div>
        </div>

        <div class="mt-4">
            <h4>Avalie essa consultoria</h4>

            <div class="rating-stars">
                <i class="fa fa-star rating-icon" data-value="1"></i>
                <i class="fa fa-star rating-icon" data-value="2"></i>
                <i class="fa fa-star rating-icon" data-value="3"></i>
                <i class="fa fa-star rating-icon" data-value="4"></i>
                <i class="fa fa-star rating-icon" data-value="5"></i>
            </div>

            <form id="ratingForm" method="POST">
                <input type="number" id="comment_rating" style="display:none" value="" name="comment_rating">
                <textarea class="form-control rating_desc" id="comment_description" name="comment_description" placeholder="Descreva como foi o atendimento, ou a prescrição de treino e dieta, ou os feedbacks, etc."></textarea>

                <div id="error-message" style="color: red; display: none; margin-top: 10px;"></div>

                <?php if (!empty($_SESSION["user_id"])): ?>
                    <button type="submit" id="submitBtn">Enviar</button>
                <?php else: ?>
                    <button type="button" id="redirectBtn" onclick="window.location.href='/sign_in'">Enviar</button>
                <?php endif; ?>
            </form>
        </div>

        <div class="mt-4">
            <h4>Outras avaliações</43>

            <div class="rated-container mt-3">
            <div class="large-number"><?= $dados["rating_detail"]["average_rating"] ?></div>
            <div class="stars">
                <?php 
                for ($i = 0; $i < 5; $i++) {
                    if ($i < $dados["rating_detail"]["average_rating"]) { ?>
                        <i class="fa fa-star checked rated-icon"></i>
                    <?php } else { ?>
                        <i class="fa fa-star rated-icon"></i>
                    <?php }
                } ?>
            </div>
            <small class="qnt-rated"><?= $dados["rating_detail"]["total_ratings"] ?> avaliações</small>
            </div>

            <div class="user-ratings">
                <?php foreach ($dados["comments"] as $comment) { ?>
                    <div class="user-rating">
                        <div class="user-info">
                            <img src="/assets/<?=$comment["profile_photo"]?>" class="user-photo" onerror="this.onerror=null;this.src='/assets/img/default-profile.jpg';">
                            <span class="user-name"><?=$comment["user_name"]?></span>
                            <i class="fas fa-ellipsis-v more-options"></i>
                        </div>
                        <div class="user-stars">
                            <div class="user-star">
                                <?php for ($i = 0; $i < 5; $i++) { ?> 
                                    <?php if ($i < $comment["rating"]) { ?>
                                        <i class="fa fa-star checked rated-icon"></i>
                                    <?php } else { ?>
                                        <i class="fa fa-star rated-icon"></i>
                                    <?php } ?>
                                <?php } ?>
                            </div>
    
                        </div>
                        <div class="user-comment">
                            <span><?= $comment["comment_text"]?></span>
                        </div>
                    </div>

                <?php }  ?>
            </div>  
        </div>
    </div>
</section>


<script src="/assets/javascripts/consulting/specificProfessionalPage.js" defer></script>

<script>
    function toggleLike() {
        const isLoggedIn = <?= json_encode(!empty($_SESSION['user_id'])) ?>;
        
        if (!isLoggedIn) {
            window.location.href = '/sign_in';
            return;
        }

        // Submit the form using fetch
        const form = document.getElementById('likeForm');
        const formData = new FormData(form);

        fetch(form.action, {
            method: 'POST',
            body: formData,
        })
        .then(response => response.json())
        .then(data => {
            if (data.success) {
                // Update the button's appearance
                const likeButton = document.getElementById('likeButton');
                if (data.user_has_liked) {
                    likeButton.innerHTML = '<i class="fa-solid fa-heart"></i>';
                } else {
                    likeButton.innerHTML = '<img src="/assets/icons/solar_heart-broken.svg" alt="Like" class="professional-service-info--social-media-icon">';
                }
            } else {
                alert('An error occurred while toggling like.');
            }
        })
        .catch(error => {
            console.error('Error:', error);
            alert('An unexpected error occurred.');
        });
    }

    document.getElementById('shareButton').addEventListener('click', function() {
        // Get the current page URL
        const currentUrl = window.location.href;

        // Create a temporary input element to use for copying the text
        const textArea = document.createElement('textarea');
        textArea.value = currentUrl; // Set the value to the current URL
        document.body.appendChild(textArea); // Append the text area to the body
        textArea.select(); // Select the text
        document.execCommand('copy'); // Copy the selected text to clipboard

        // Remove the text area from the document
        document.body.removeChild(textArea);

        // Show the confirmation message
        const copyMessage = document.getElementById('copyMessage');
        copyMessage.style.display = 'block'; // Make the message visible

        // Hide the message after 10 seconds
        setTimeout(() => {
            copyMessage.style.display = 'none';
        }, 10000); // 10 seconds
    });


</script>