<section id="ServiceHeadingSection">
    <div class="container">
        <div class="row">
            <div class="col-12 col-lg-8">

                <div class="service-header--container">
                    <div class="service-header--lables-contaiers">
                        <label class="spot-label-orange">FITNESS</label>
                        <label class="spot-label-green">Novo na plataforma</label>
                    </div>
                    <h1 class="service-page--service-title">Centro Fitness SCS</h1>
                </div>

                <div class="professional-service-slider--container">
                    <div class="swiper mySwiper">
                        <div class="swiper-wrapper">
                            <div class="swiper-slide professional-service-slider--item">
                                <img src="/assets/img/models/m1.png" alt="">
                            </div>
                            <div class="swiper-slide professional-service-slider--item">
                                <img src="/assets/img/models/m2.png" alt="">
                            </div>
                            <div class="swiper-slide professional-service-slider--item">
                                <img src="/assets/img/models/m3.png" alt="">
                            </div>
                            <div class="swiper-slide professional-service-slider--item">
                                <img src="/assets/img/models/m2.png" alt="">
                            </div>
                            <div class="swiper-slide professional-service-slider--item">
                                <img src="/assets/img/models/m3.png" alt="">
                            </div>
                        </div>

                        <div class="professional-service-slider--button-next"><i class="fa-solid fa-chevron-right"></i></div>
                        <div class="professional-service-slider--button-prev"><i class="fa-solid fa-chevron-left"></i></div>

                        <div class="professional-service-slider--pagination"></div>
                    </div>

                </div>
            </div>
            <div class="col-12 col-lg-4 professional-service-info--container">
                <div class="professional-service-info--social-media-container">
                    <img src="/assets/icons/share.svg" alt="" class="professional-service-info--social-media-icon">
                    <img src="/assets/icons/solar_heart-broken.svg" alt="" class="professional-service-info--social-media-icon">
                    <img src="/assets/icons/location.svg" alt="" class="professional-service-info--social-media-icon">
                </div>
                
                <div class="professional-service-info--features-container">
                    <div class="professional-service-info--feature-item">
                        <div class="professional-service-feature-item--feature-description">
                            <i class="far fa-heart gray-icon"></i>
                            <p class="professional-service-feature--name">Curtidas</p>
                        </div>

                        <div class="professional-service-feature--intensity-container">
                            <p class="professional-service-feature--intensity-text">
                                87
                            </p>
                        </div>
                    </div>
                    <div class="professional-service-info--feature-item">
                        <div class="professional-service-feature-item--feature-description">
                            <i class="far fa-eye gray-icon"></i>
                            <p class="professional-service-feature--name">Vizualizações</p>
                        </div>

                        <div class="professional-service-feature--intensity-container">
                            <p class="professional-service-feature--intensity-text">
                                500
                            </p>
                        </div>
                    </div>
                    <div class="professional-service-info--feature-item">
                        <div class="professional-service-feature-item--feature-description">
                            <i class="far fa-comments gray-icon"></i>
                            <p class="professional-service-feature--name">Comentários</p>
                        </div>

                        <div class="professional-service-feature--intensity-container">
                            <p class="professional-service-feature--intensity-text">
                                10
                            </p>
                        </div>
                    </div>
                </div>

                <div class="professional-service-info--text-description-container">
                    <p class="professional-service-info--text-description">
                    Um plano de desenvolvimento para atletas de alta performance é essencial para maximizar seu potencial. Com avaliação holística, metas claras, treinamento multidisciplinar. 
                    </p>
                </div>

                <div class="professional-service-info--contact-container">
                    <div class="professional-service-info--contact-item">
                        <i class="fas fa-phone gray-icon"></i>
                        <p class="professional-service-info--contact-text">+55 (11) 98302-0692</p>
                    </div>
                    <div class="professional-service-info--contact-item">
                        <i class="fas fa-envelope gray-icon"></i>
                        <p class="professional-service-info--contact-text">fake.email@gmail.com</p>
                    </div>
                </div>

                <div class="professional-service-info--chat-action-container">
                    <form action="" method="POST">
                        <input type="text" style="display: none" value="<?=!empty($providerId) ? $providerId : ''?>">
                        <button type="submit" class="spot-btn-dark-orange onhover-broom">
                            <span>
                                Entrar em contato pelo Chat
                            </span>
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

<section id="fpDescriptionSection">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="fp-description-title-area row">
                    <h1 class="spot-text-title">Planos</h1>
                    <p class="spot-text-title-watermark">Planos</p>
                </div>          
            </div>
        </div>

        <div class="row">
            <div class="swiper plans-swiper">
                <div class="swiper-wrapper">
                    <div class="swiper-slide">
                        <div class="card professional-card" style="width: 18rem;">
                            <div class="card-body text-center">
                                <h5 class="card-title">Plano completo semestral</h5>
                                <p class="card-text">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ventore voluptatem ratione</p>
                                <div class="plan-price">
                                    <h6>R$ 600</h6>
                                    <small>/2 meses</small>
                                </div>
                            </div>
                            <h6 class="mt-2 p-1 text-center">Benefícios inclusos</h6>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item"><i class="fas fa-dumbbell"></i> Treino periodizado</li>
                                <li class="list-group-item"><i class="fab fa-apple"></i> Dieta</li>
                                <li class="list-group-item"><i class="fas fa-person"></i> Prescrição de alongamentos</li>
                            </ul>
                        </div>
                    </div>

                    <div class="swiper-slide">
                        <div class="card professional-card" style="width: 18rem;">
                            <div class="card-body text-center">
                                <h5 class="card-title">Plano completo semestral</h5>
                                <p class="card-text">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ventore voluptatem ratione</p>
                                <div class="plan-price">
                                    <h6>R$ 600</h6>
                                    <small>/2 meses</small>
                                </div>
                            </div>
                            <h6 class="mt-2 p-1 text-center">Benefícios inclusos</h6>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item"><i class="fas fa-dumbbell"></i> Treino periodizado</li>
                                <li class="list-group-item"><i class="fab fa-apple"></i> Dieta</li>
                                <li class="list-group-item"><i class="fas fa-person"></i> Prescrição de alongamentos</li>
                            </ul>
                        </div>
                    </div>

                    <div class="swiper-slide">
                        <div class="card professional-card" style="width: 18rem;">
                            <div class="card-body text-center">
                                <h5 class="card-title">Plano completo semestral</h5>
                                <p class="card-text">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ventore voluptatem ratione</p>
                                <div class="plan-price">
                                    <h6>R$ 600</h6>
                                    <small>/2 meses</small>
                                </div>
                            </div>
                            <h6 class="mt-2 p-1 text-center">Benefícios inclusos</h6>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item"><i class="fas fa-dumbbell"></i> Treino periodizado</li>
                                <li class="list-group-item"><i class="fab fa-apple"></i> Dieta</li>
                                <li class="list-group-item"><i class="fas fa-person"></i> Prescrição de alongamentos</li>
                            </ul>
                        </div>
                    </div>

                    <div class="swiper-slide">
                        <div class="card professional-card" style="width: 18rem;">
                            <div class="card-body text-center">
                                <h5 class="card-title">Plano completo semestral</h5>
                                <p class="card-text">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ventore voluptatem ratione</p>
                                <div class="plan-price">
                                    <h6>R$ 600</h6>
                                    <small>/2 meses</small>
                                </div>
                            </div>
                            <h6 class="mt-2 p-1 text-center">Benefícios inclusos</h6>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item"><i class="fas fa-dumbbell"></i> Treino periodizado</li>
                                <li class="list-group-item"><i class="fab fa-apple"></i> Dieta</li>
                                <li class="list-group-item"><i class="fas fa-person"></i> Prescrição de alongamentos</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="lp-control-swiper-categorie-button lp-control-swiper-categorie-button-next"><i class="fa-solid fa-chevron-right"></i></div>
                <div class="lp-control-swiper-categorie-button lp-control-swiper-categorie-button-prev"><i class="fa-solid fa-chevron-left"></i></div>
            </div>
        </div>
    </div>
</section>


<script src="/assets/javascripts/consulting/specificProfessionalPage.js" defer></script>