<div class="container">
<span class="over-flow-atras">PLANOS</span>

<h2 class="mb-4"><strong>Nossos Planos</strong></h2>

    <div class="row mb-3 text-center mt-5">
      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal ">Grátis</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title">$0 <small class="text-muted">/ mês</small></h1>
            <ul class="list-unstyled mt-3 mb-4">
              <li>Selo de Verificação</li>
              <li>Seção Exclusiva nas Pesquisas</li>
              <li class="bloq"><s>Criar até 3 consultorias</s></li>
              <li class="bloq"><s>Dashboard de Vendas</s></li>
            </ul>
            <button type="button" class="btn btn-lg btn-block btn-outline-primary">Cadastre-se de graça</button>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal text-primary">Pro</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title">$15 <small class="text-muted">/ mês</small></h1>
            <ul class="list-unstyled mt-3 mb-4">
              <li>Selo de Verificação</li>
              <li>Seção Exclusiva nas Pesquisas</li>
              <li>+ Criar até 3 consultorias</li>
              <li class="bloq"><s>Dashboard de Vendas</s></li>
            </ul>
            <button type="button" class="btn btn-lg btn-block btn-primary">Conhecer</button>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal" style="color:var(--orange-color)">Premium</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title">$29 <small class="text-muted">/ mês</small></h1>
            <ul class="list-unstyled mt-3 mb-4">
              <li>Selo de Verificação</li>
              <li>Seção Exclusiva nas Pesquisas</li>
              <li>Criar até 3 consultorias</li>
              <li>+ Dashboard de Vendas</li>
            </ul>
            <button type="button" class="btn btn-lg btn-block btn-primary btn-premium">Contate-nos</button>
          </div>
        </div>
      </div>
    </div>
  </div>
