
<main role="main" class="container">
  <section id="success" class="hidden">
    <div class="jumbotron" class='jumbotron'>
      <p class="lead"> Obrigado pelo seu pedido! 🎉 Um e-mail de confirmação será enviado para <span id="customer-email"></span>.
      <br>
      Se tiver alguma dúvida, envie um e-mail para <a href="mailto:spotfit@outlook.com.br" style='text-decoration: none;'>spotfit@outlook.com.br</a> </p>
      <a href="/landing_page"  class="btn btn-primary" style='text-decoration: none; color:white;'>Voltar para o Início <i class="fa-solid fa-rotate-left"></i></a>
    </div>
  </section>
</main>

<script src="https://js.stripe.com/v3/"></script>
<script src="/assets/javascripts/success.js"></script> 



