<div class="container mb-5 mt-5">
  <div class="row">
    
    <div class="col d-none d-md-block">
      <?php if(isset($_GET['new_user']) && $_GET['new_user'] == '1'){ ?>
          <div class="alert alert-success" role="alert">
              Bem vindo! Faça login usando o email e a senha que você acabou de criar
          </div>
      <?php } ?>
      <?php if(isset($_GET['logged']) && $_GET['logged'] == '0'){ ?>
          <div class="alert alert-danger" role="alert">
              Email ou senha incorretos
          </div>
      <?php } ?>
        <img src="/assets/img/img_SignIn.png" alt="Imagem" class="img-fluid" width="100%">
    </div>
  
    <form class="col-md-6 needs-validation form-signIn" novalidate method="POST" action="/sign_in/authenticate">
      
      <div class="form-row">

        <span class="over-flow-atras">LOGIN</span>

        <div class="row">
          <div class="col">
              <h1 class="mb-4"><strong>Login</strong></h1>
          </div>
          <div class="col-auto ml-auto">
             <a href="/landing_page" style="color:var(--white-color)"><i class="fas fa-home"></i></a> 
          </div>
        </div>


        <div class="form-group mb-3">
            <label for="email">E-mail</label>
            <input type="email" class="form-control" id="email" name="email" autocomplete="email" required>
        </div>
        <div class="form-group mb-3">
            <label for="password">Senha</label>
            <input type="password" class="form-control" id="password" name="password" autocomplete="password" required>
        </div>

        <a href="/forgotPassword" class="forgotPassword">Esqueceu sua senha?</a>
        
        <button type="submit" class="btn btn-primary btn-block mb-3">Entrar</button>

        <div class="link">
          <p>Ainda não tem conta? <a href="/sign_up" class="linkSignUp">  Cadastra-se </a></p>
        </div>
       

      </div>
    </form>

    
  </div>

</div>


<script src="/assets/javascripts/formValidation.js" defer></script>

