<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="stylesheet" href="/assets/stylesheets/faq.css">
  
  <script src="/assets/javascripts/faq.js" defer></script>
  
</head>

<body>
  <div class="container mt-5">
    
    <h3 class="mb-4">Perguntas Frequentes</h3>
    
    <div class="card mt-3">
      <div class="card-header" tabindex="0">
        <div class="d-flex justify-content-between align-items-center w-100">
          <h6>Como faço para começar?</h6>
          <i class="fas fa-plus"></i>
        </div>
      </div>
      <div class="card-body">
        Para começar, você pode seguir os seguintes passos...
      </div>
    </div>

    <div class="card mt-3">
      <div class="card-header" tabindex="0">
        <div class="d-flex justify-content-between align-items-center w-100">
          <h6>Qual é a política de reembolso?</h6>
          <i class="fas fa-plus"></i>
        </div>
      </div>
      <div class="card-body">
        Nossa política de reembolso permite que você...
      </div>
    </div>

    <div class="card mt-3">
      <div class="card-header" tabindex="0">
        <div class="d-flex justify-content-between align-items-center w-100">
          <h6>Como posso entrar em contato?</h6>
          <i class="fas fa-plus"></i>
        </div>
      </div>
      <div class="card-body">
        Você pode entrar em contato conosco através do...
      </div>
    </div>

    <div class="card mt-3">
      <div class="card-header" tabindex="0">
        <div class="d-flex justify-content-between align-items-center w-100">
          <h6>Como posso entrar em contato?</h6>
          <i class="fas fa-plus"></i>
        </div>
      </div>
      <div class="card-body">
        Você pode entrar em contato conosco através do...
      </div>
    </div>

    <div class="card mt-3">
      <div class="card-header" tabindex="0">
        <div class="d-flex justify-content-between align-items-center w-100">
          <h6 class="text-gray-dark">Como posso entrar em contato?</h6>
          <i class="fas fa-plus"></i>
        </div>
      </div>
      <div class="card-body">
        Você pode entrar em contato conosco através do...
      </div>
    </div>

    <div class="container-fluid">
      <div class="row">
        <form class="col-md-6 form-faq">
          <div class="mb-4">
            <h1 class="h3 mb-3 font-weight">Envie sua dúvida</h1>
          </div>

          <div class="form-label-group">
            <label for="inputText">Nome</label>
            <input type="text" id="inputText" class="form-control" required autofocus>
          </div>

          <div class="form-label-group">
            <label for="inputEmail">E-mail</label>
            <input type="email" id="inputEmail" class="form-control" required>
          </div>

          <div class="form-label-group">
            <label for="inputSubject">Assunto</label>
            <textarea id="inputSubject" class="form-control" required></textarea>
          </div>

          <button class="btn btn-primary btn-block" type="submit">Enviar</button>

        </form>
        <div class="col d-none d-md-block">
          <img src="/assets/img/muscle-vegetables.png" alt="Imagem" class="img-fluid" >
        </div>
      </div>
    </div>


  
</body>
</html>
