<div class="container mt-5">
  <span class="over-flow-atras">FAQ</span>

  <h2 class="mb-4"><strong>Perguntas Frequentes</strong></h2>
  
  <div class="cards">
    <div class="card mt-3">
      <div class="card-header" tabindex="0">
        <div class="d-flex justify-content-between align-items-center w-100">
          <h6>O que é a Spotfit?</h6>
          <i class="fas fa-plus"></i>
        </div>
      </div>
      <div class="card-body">
        Spotfit é uma plataforma dedicada ao bem-estar físico e mental, oferecendo programas de treinamento personalizados e inovadores para ajudar você a alcançar seus objetivos de saúde.
      </div>
    </div>

    <div class="card mt-3">
      <div class="card-header" tabindex="0">
        <div class="d-flex justify-content-between align-items-center w-100">
          <h6>Como funciona a Spotfit?</h6>
          <i class="fas fa-plus"></i>
        </div>
      </div>
      <div class="card-body">
        Na Spotfit, você cria um perfil, define suas metas de saúde e bem-estar, e com base nisso, nossa equipe de especialistas cria um programa de treinamento personalizado para você. Nossos programas incluem exercícios físicos, planos de alimentação e técnicas de mindfulness.
      </div>
    </div>

    <div class="card mt-3">
      <div class="card-header" tabindex="0">
        <div class="d-flex justify-content-between align-items-center w-100">
          <h6>Quem pode usar a Spotfit?</h6>
          <i class="fas fa-plus"></i>
        </div>
      </div>
      <div class="card-body">
        A Spotfit é projetada para qualquer pessoa interessada em melhorar sua saúde física e mental, independentemente do nível de condicionamento físico. Nossos programas são personalizados para atender às necessidades individuais de cada usuário.
      </div>
    </div>

    <div class="card mt-3">
      <div class="card-header" tabindex="0">
        <div class="d-flex justify-content-between align-items-center w-100">
          <h6>Quais tipos de programas a Spotfit oferece?</h6>
          <i class="fas fa-plus"></i>
        </div>
      </div>
      <div class="card-body">
        Oferecemos uma variedade de programas que incluem treinos de força, cardio, alongamento, yoga, meditação e muito mais. Todos os programas são adaptados aos seus objetivos e nível de condicionamento físico.     
      </div>
    </div>

    <div class="card mt-3">
      <div class="card-header" tabindex="0">
        <div class="d-flex justify-content-between align-items-center w-100">
          <h6>Preciso de equipamentos especiais para seguir os programas da Spotfit?</h6>
          <i class="fas fa-plus"></i>
        </div>
      </div>
      <div class="card-body">
        Não, muitos dos nossos programas são projetados para serem realizados com pouco ou nenhum equipamento. Para aqueles que desejam usar equipamentos, oferecemos opções que incluem o uso de pesos livres, faixas de resistência e outros equipamentos de fácil acesso.
      </div>
    </div>

    <div class="card mt-3">
      <div class="card-header" tabindex="0">
        <div class="d-flex justify-content-between align-items-center w-100">
          <h6>Como faço para começar?</h6>
          <i class="fas fa-plus"></i>
        </div>
      </div>
      <div class="card-body">
        É simples! Basta se inscrever na nossa plataforma, preencher um questionário sobre suas metas e preferências, e nossa equipe irá criar um programa personalizado para você. Você pode acessar seus treinos e planos de alimentação diretamente pelo nosso aplicativo ou site.
      </div>
    </div>


    <div class="card mt-3">
      <div class="card-header" tabindex="0">
        <div class="d-flex justify-content-between align-items-center w-100">
          <h6>A Spotfit oferece suporte ao cliente?</h6>
          <i class="fas fa-plus"></i>
        </div>
      </div>
      <div class="card-body">
        Sim, temos uma equipe de suporte ao cliente disponível para ajudar com qualquer dúvida ou problema que você possa ter. Você pode entrar em contato conosco através do nosso chat ao vivo no site, email ou telefone.
      </div>
    </div>
 

    <div class="card mt-3">
      <div class="card-header" tabindex="0">
        <div class="d-flex justify-content-between align-items-center w-100">
          <h6>Posso mudar meus objetivos após iniciar um programa?</h6>
          <i class="fas fa-plus"></i>
        </div>
      </div>
      <div class="card-body">
         Claro! Entendemos que seus objetivos podem evoluir ao longo do tempo. Você pode atualizar suas metas a qualquer momento no seu perfil, e ajustaremos seu programa de acordo com suas novas necessidades.
      </div>
    </div>
  

    <div class="card mt-3">
      <div class="card-header" tabindex="0">
        <div class="d-flex justify-content-between align-items-center w-100">
          <h6>Como a Spotfit protege minha privacidade?</h6>
          <i class="fas fa-plus"></i>
        </div>
      </div>
      <div class="card-body">
        Levamos sua privacidade muito a sério. Seus dados são protegidos por criptografia e usamos as melhores práticas de segurança para garantir que suas informações pessoais estejam seguras.
      </div>
    </div>

    <div class="card mt-3">
        <div class="card-header" tabindex="0">
          <div class="d-flex justify-content-between align-items-center w-100">
            <h6>Posso cancelar minha assinatura a qualquer momento?</h6>
            <i class="fas fa-plus"></i>
          </div>
        </div>
        <div class="card-body">
          Sim, você pode cancelar sua assinatura a qualquer momento. Não há contratos de longo prazo e você pode sair quando quiser, sem complicações.
        </div>
      </div>
    </div>



  <!--form faq-->
  <div class="row">
    <form class="col-md-6 needs-validation form-faq" novalidate>
      <div class="mb-4">
        <h3 class="h3 mb-3">Envie sua dúvida</h3>
      </div>

      <div class="form-label-group mb-3">
        <label for="inputText">Nome</label>
        <input type="text" id="inputText" class="form-control " required autofocus>
      </div>

      <div class="form-label-group mb-3">
        <label for="inputEmail">E-mail</label>
        <input type="email" id="inputEmail" class="form-control " required>
      </div>

      <div class="form-label-group mb-3">
        <label for="inputSubject">Assunto</label>
        <textarea id="inputSubject" class="form-control" required></textarea>
      </div>

      <button class="btn btn-primary btn-block" type="submit">Enviar</button>

    </form>
    <div class="col d-none d-md-block">
      <img src="/assets/img/muscle-vegetables.png" alt="Imagem" class="img-fluid" >
    </div>
  </div>

<script src="/assets/javascripts/formValidation.js" defer></script>

