<div class="d-md-flex flex-md-equal w-100 mission">
      <div class="bg-card mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden">
        <div class="my-3 py-3">
          <h2 class="display-5">Missão</h2>
          <p class="lead">E outra descrição mais engraçadinha aindaaaaa.</p>
        </div>
        <div class="about-card shadow-sm mx-auto" style="width: 70%; height: 200px; border-radius: 21px 21px 0 0;">
            <p class="text-black">aaaaaaa</p>
        </div>
      </div>

      <div class="bg-card mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden">
        <div class="my-3 py-3">
          <h2 class="display-5">Vissão</h2>
          <p class="lead">E outra descrição mais engraçadinha ainda.</p>
        </div>
        <div class="bg-light shadow-sm mx-auto" style="width: 70%; height: 200px; border-radius: 21px 21px 0 0;"></div>
      </div>

      <div class="bg-card mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden">
        <div class="my-3 py-3">
          <h2 class="display-5">Valores</h2>
          <p class="lead">E outra descrição mais engraçadinha ainda.</p>
        </div>
        <div class="bg-light shadow-sm mx-auto" style="width: 70%; height: 200px; border-radius: 21px 21px 0 0;"></div>
      </div>
</div>
      
<div class="container">
    <span class="over-flow-atras">Nosso Time</span>
    <h2 class="mb-4"><strong>Nosso Time</strong></h2>
   
    <div class="card flex-md-row mb-4 shadow-sm h-md-250">
        <div class="card-body d-flex flex-column align-items-start">
            <strong class="d-inline-block mb-2 text-primary">Desevolvedora</strong>
            <h3 class="mb-3">Ana Eliza Yukimoto de Oliveira</h3>
            <h6 class="card-text mb-auto">Este é um card maior com suporte a texto, em baixo, como uma introdução mais natural ao conteúdo adicional. Este conteúdo é um pouco maior, para demonstração.</p>
            <ul class="list-inline">
                <li class="list-inline-item"><a class="footer-link" href="#"><i class="fab fa-twitter"></i></a></li>
                <li class="list-inline-item"><a class="footer-link" href="#"><i class="fab fa-instagram"></i></a></li>
                <li class="list-inline-item"><a class="footer-link" href="#"><i class="fab fa-facebook"></i></a></li>
            </ul>
        </div>
        <img class="card-img-right flex-auto d-none d-lg-block" src="assets/img/devs/AnaEliza.jpeg" style="max-width: auto; height: 200px;" alt="Imagem de capa do card">
    </div>
       
    <div class="card flex-md-row mb-4 shadow-sm ">
    <img class="card-img-right flex-auto d-none d-lg-block" src="assets/img/devs/Natan.jpg" style="max-width: auto; height: 200px;" alt="Imagem de capa do card">
        <div class="card-body d-flex flex-column align-items-start">
            <strong class="d-inline-block mb-2 text-primary">Título do Card</strong>
            <h3 class="mb-3">Gustavo</h3>
            <p>Este é um card maior com suporte a texto, em baixo, como uma introdução mais natural ao conteúdo adicional. Este conteúdo é um pouco maior, para demonstração.</p>
            <ul class="list-inline">
                <li class="list-inline-item"><a class="footer-link" href="#"><i class="fab fa-twitter"></i></a></li>
                <li class="list-inline-item"><a class="footer-link" href="#"><i class="fab fa-instagram"></i></a></li>
                <li class="list-inline-item"><a class="footer-link" href="#"><i class="fab fa-facebook"></i></a></li>
            </ul>
        </div>
        
    </div>

    <div class="card flex-md-row mb-4 shadow-sm h-md-250">
        <div class="card-body d-flex flex-column align-items-start">
            <strong class="d-inline-block mb-2 text-primary">Título do Card</strong>
            <h3 class="mb-3">Gustavo</h3>
            <p class="card-text mb-auto">Este é um card maior com suporte a texto, em baixo, como uma introdução mais natural ao conteúdo adicional. Este conteúdo é um pouco maior, para demonstração.</p>
            <ul class="list-inline">
                <li class="list-inline-item"><a class="footer-link" href="#"><i class="fab fa-twitter"></i></a></li>
                <li class="list-inline-item"><a class="footer-link" href="#"><i class="fab fa-instagram"></i></a></li>
                <li class="list-inline-item"><a class="footer-link" href="#"><i class="fab fa-facebook"></i></a></li>
            </ul>
        </div>
        <img class="card-img-right flex-auto d-none d-lg-block" src="assets/img/devs/AnaEliza.jpeg" style="max-width: auto; height: 200px;" alt="Imagem de capa do card">
    </div>


    <div class="card flex-md-row mb-4 shadow-sm ">
    <img class="card-img-right flex-auto d-none d-lg-block" src="assets/img/devs/Natan.jpg" style="max-width: auto; height: 200px;" alt="Imagem de capa do card">
        <div class="card-body d-flex flex-column align-items-start">
            <strong class="d-inline-block mb-2 text-primary">Título do Card</strong>
            <h3 class="mb-3">Natan </h3>
            <p>Este é um card maior com suporte a texto, em baixo, como uma introdução mais natural ao conteúdo adicional. Este conteúdo é um pouco maior, para demonstração.</p>
            <ul class="list-inline">
                <li class="list-inline-item"><a class="footer-link" href="#"><i class="fab fa-twitter"></i></a></li>
                <li class="list-inline-item"><a class="footer-link" href="#"><i class="fab fa-instagram"></i></a></li>
                <li class="list-inline-item"><a class="footer-link" href="#"><i class="fab fa-facebook"></i></a></li>
            </ul>
        </div>
        
    </div>

    <div class="card flex-md-row mb-4 shadow-sm h-md-250">
        <div class="card-body d-flex flex-column align-items-start">
            <strong class="d-inline-block mb-2 text-primary">Título do Card</strong>
            <h3 class="mb-3">Pedro</h3>
            <p class="card-text mb-auto">Este é um card maior com suporte a texto, em baixo, como uma introdução mais natural ao conteúdo adicional. Este conteúdo é um pouco maior, para demonstração.</p>
            <ul class="list-inline">
                <li class="list-inline-item"><a class="footer-link" href="#"><i class="fab fa-twitter"></i></a></li>
                <li class="list-inline-item"><a class="footer-link" href="#"><i class="fab fa-instagram"></i></a></li>
                <li class="list-inline-item"><a class="footer-link" href="#"><i class="fab fa-facebook"></i></a></li>
            </ul>
        </div>
        <img class="card-img-right flex-auto d-none d-lg-block" src="assets/img/devs/AnaEliza.jpeg" style="max-width: auto; height: 200px;" alt="Imagem de capa do card">
    </div>

    </div>
</div>
