<div class="container-fluid mb-5">
    <div class="row">
        <div class="col-md bg-card mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden">
            <h2>Nossa <span class="text-primary">Missão</span></h2>
            <i class="fas fa-bullseye text-primary" style="font-size:90px; transform: translateY(30px);"></i>

            <div class="d-flex flex-column h-100">
                <div class="bg-light shadow-sm mx-auto flex-grow-1" style="border-radius: 21px 21px 0 0;">
                    <p class="textAbout">Facilitar um estilo de vida saudável através da tecnologia, fornecendo ferramentas e recursos acessíveis para melhorar a saúde e o bem-estar dos usuários.</p>
                </div>
            </div>
        </div>

        <div class="col-md bg-card mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden">
            <h2>Nossa <span class="text-warning">Visão</span> </h2>
            <i class="fas fa-eye text-warning" style="font-size:90px; transform: translateY(30px);"></i>

            <div class="d-flex flex-column h-100">
                <div class="bg-light shadow-sm mx-auto flex-grow-1" style="border-radius: 21px 21px 0 0;">
                    <p class="textAbout">Ser a plataforma líder em consultoria fitness, reconhecida pela transformação positiva na vida das pessoas através da promoção de hábitos saudáveis e do bem-estar.</p>
                </div>
            </div>
        </div>

        <div class="col-md bg-card pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden">
            <h2 >Nossos <span class="text-info">Valores</span> </h2>
            <i class="fas fa-puzzle-piece text-info" style="font-size:90px; transform: translateY(30px);" ></i>

            <div class="d-flex flex-column h-100">
                <div class="bg-light shadow-sm mx-auto flex-grow-1" style="border-radius: 21px 21px 0 0;">
                    <p class="textAbout">Nosso compromisso está em inovar constantemente, personalizar cada experiência, fortalecer conexões significativas, buscar a excelência em tudo que fazemos e promover o bem-estar integral dos nossos usuários.</p>
                </div>
            </div>
        </div>
    </div>
</div>


      
<div class="container">
    <span class="over-flow-atras">Nosso Time</span>
    <h2 class="mb-5"><strong>Nosso Time</strong></h2>
   
    <div class="card flex-md-row mb-4 shadow-sm h-md-250">
        <div class="card-body d-flex flex-column align-items-start">
            <strong class="d-inline-block mb-2 text-danger">Desenvolvedora Full Stack</strong>
            <h3 class="mb-3">Ana Eliza Yukimoto de Oliveira</h3>
            <h6 class="card-text mb-auto mb-3">Ao realizar o curso online de Introdução à Linguagem de Programação, me encontrei na tecnologia. Hoje sou técnica em Desenvolvimento de Sitemas e estou na Faculdade de Informática para Negócios, onde encontrei a combinação de duas áreas pelas quais sou apaixonada, gestão e tecnologia. Em resumo, sou uma pessoa otimista, criativa e vontade constante de aprender.</p>
            <ul class="list-inline"> 
                <li class="list-inline-item "><a class="footer-link text-danger" href="https://github.com/AnaYukimoto"><i class="fab fa-github"></i></a></li>
                <li class="list-inline-item"><a class="footer-link text-danger" href="www.linkedin.com/in/anaelizayukimoto"><i class="fab fa-linkedin"></i></a></li>
                <li class="list-inline-item"><a class="footer-link text-danger" href="https://www.instagram.com/anaeliza_yuki/"><i class="fab fa-instagram"></i></a></li>
            </ul>
        </div>
        <img class="card-img flex-auto d-none d-lg-block" src="assets/img/devs/AnaEliza.jpeg" style="max-width: 180px; object-fit: cover;" alt="Imagem de capa do card">
    </div>
       
    <div class="card flex-md-row mb-4 shadow-sm ">
    <img class="card-img flex-auto d-none d-lg-block" src="assets/img/devs/Barros.jpeg" style="max-width: 180px; height: auto;" alt="Imagem de capa do card">
        <div class="card-body d-flex flex-column align-items-start">
            <strong class="d-inline-block mb-2 text-primary">Analista de Suporte Técnico</strong>
            <h3 class="mb-3">Gustavo Barros Silva </h3>
            <p  class="card-text mb-auto mb-3">Sou estudante de Informática para Negócios na Fatec Adib Moisés. Iniciei na área no Ensino Médio técnico na ETEC e fiz cursos no SENAI. Sempre fui apaixonado por tecnologia e estou sempre buscando expandir meus conhecimentos.</p>
            <ul class="list-inline">
                <li class="list-inline-item"><a class="footer-link text-primary" href="https://github.com/6ustavobarros"><i class="fab fa-github"></i></a></li>
                <li class="list-inline-item"><a class="footer-link text-primary" href="https://www.linkedin.com/in/6ustavobarros"><i class="fab fa-linkedin"></i></a></li>
                <li class="list-inline-item"><a class="footer-link text-primary" href="https://www.instagram.com/baarrozz/"><i class="fab fa-instagram"></i></a></li>
            </ul>
        </div>
        
    </div>

    <div class="card flex-md-row mb-4 shadow-sm h-md-250">
        <div class="card-body d-flex flex-column align-items-start">
            <strong class="d-inline-block mb-2 text-success">Desenvolvedor Full Stack</strong>
            <h3 class="mb-3">Gustavo Inacio Lacerda</h3>
            <p class="card-text mb-auto mb-3">
            Desde os 12 anos, minha paixão pela programação tem sido uma força motriz em minha vida. Sempre me fascinei por resolver problemas do mundo real e desenvolver soluções inovadoras que tornam o dia a dia das pessoas mais fácil. Atualmente, estou desenvolvendo uma solução de consultoria fitness, combinando tecnologia e bem-estar para ajudar as pessoas a atingirem seus objetivos de saúde e fitness de maneira mais eficiente.
            </p>
            <ul class="list-inline">
                <li class="list-inline-item"><a class="footer-link text-success" href="https://www.linkedin.com/in/gustavo-inacio-lacerda/"><i class="fab fa-github"></i></a></li>
                <li class="list-inline-item"><a class="footer-link text-success" href="https://www.linkedin.com/in/gustavo-inacio-lacerda/"><i class="fab fa-linkedin"></i></a></li>
                <li class="list-inline-item"><a class="footer-link text-success" href="https://www.instagram.com/gutiinacio/"><i class="fab fa-instagram"></i></a></li>
            </ul>
        </div>
        <img class="card-img flex-auto d-none d-lg-block" src="assets/img/devs/Inacio.jpg" style="max-width: 180px; object-fit:cover; transform: scaleX(-1);" alt="Imagem de capa do card">
    </div>


    <div class="card flex-md-row mb-4 shadow-sm ">
    <img class="card-img flex-auto d-none d-lg-block" src="assets/img/devs/Natan.jpg" style="max-width: 180px; object-fit: cover;" alt="Imagem de capa do card">
        <div class="card-body d-flex flex-column align-items-start">
            <strong class="d-inline-block mb-2 text-warning">Desenvolvedor Back-End</strong>
            <h3 class="mb-3">Natan Rocha Barbosa </h3>
            <p class="card-text mb-auto mb-3">Sou estudante de Informática para Negócios na Fatec São Bernardo do Campo e desenvolvedor de sistemas de informação na Moltrio, trabalhando com Ruby on Rails. Tenho interesse em desenvolvimento web e banco de dados. Iniciei na área no Ensino Médio técnico na Etec e me especializei com cursos no Senac e Instituto Proa. Minhas experiências e estudos me proporcionaram um conhecimento sólido em tecnologia. Me siga nas redes sociais para saber mais!</p>
            <ul class="list-inline">
                <li class="list-inline-item"><a class="footer-link text-warning" href="https://github.com/NatanBarbosa"><i class="fab fa-github"></i></a></li>
                <li class="list-inline-item"><a class="footer-link text-warning" href="https://www.linkedin.com/in/natanrochabarbosa/"><i class="fab fa-linkedin"></i></a></li>
                <li class="list-inline-item"><a class="footer-link text-warning" href="https://www.instagram.com/natan_rocha_/"><i class="fab fa-instagram"></i></a></li>
            </ul>
        </div>
        
    </div>

    <div class="card flex-md-row mb-4 shadow-sm h-md-250">
        <div class="card-body d-flex flex-column align-items-start">
            <strong class="d-inline-block mb-2 text-info">Analista de Suporte</strong>
            <h3 class="mb-3">Pedro Gustavo Junior</h3>
            <p class="card-text mb-auto mb-3">Atualmente, sou aluno da Fatec São Bernardo, cursando Informática para Negócios, e estagiário de infraestrutura de redes na empresa Termocolor. Tive meu primeiro contato com a tecnologia durante um curso de Logística, onde descobri meu interesse pela área. Isso me levou a ingressar na faculdade e a realizar diversos cursos em plataformas como a Udemy. </p>
            <ul class="list-inline">
                <li class="list-inline-item"><a class="footer-link text-info" href="https://github.com/PedroGustavo99"><i class="fab fa-github"></i></a></li>
                <li class="list-inline-item"><a class="footer-link text-info" href=www.linkedin.com/in/pedro-gustavo-junior"><i class="fab fa-linkedin"></i></a></li>
                <li class="list-inline-item"><a class="footer-link text-info" href="https://www.instagram.com/junim_pedro?igsh=ZzU4b2dxbHB0aG8z"><i class="fab fa-instagram"></i></a></li>
            </ul>
        </div>
        <img class="card-img flex-auto d-none d-lg-block" src="assets/img/devs/Pedro.jpg" style="max-width: 180px; object-fit: cover;" alt="Imagem de capa do card">
    </div>

    </div>
</div>
