<div class="d-md-flex flex-md-equal w-100 mission">
    <div class="bg-card mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden">
        <h2>Nossa <span class="text-primary">Missão</span></h2>
        <i class="fas fa-bullseye text-primary" style="font-size:90px; transform: translateY(30px);"></i>

        <div class="about-card shadow-sm mx-auto" style="width: 70%; height: 200px; border-radius: 21px 21px 0 0;">
            <p class="textAbout">E outra descrição mais engraçadinha ainda. E outra descrição mais engraçadinha ainda.E outra descrição mais engraçadinha ainda.</p>
        </div>
    </div>

      <div class="bg-card mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden">
        <h2>Nossa <span class="text-warning">Visão</span> </h2>
        <i class="fas fa-eye text-warning" style="font-size:90px; transform: translateY(30px);"></i>

        <div class="bg-light shadow-sm mx-auto" style="width: 70%; height: 200px; border-radius: 21px 21px 0 0;">
        <p class="textAbout">E outra descrição mais engraçadinha ainda. E outra descrição mais engraçadinha ainda. E outra descrição mais engraçadinha ainda.</p>
        </div>
      </div>

      <div class="bg-card mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden">
        <h2 >Nossos <span class="text-info">Valores</span> </h2>
        <i class="fas fa-puzzle-piece text-info" style="font-size:90px; transform: translateY(30px);" ></i>

        <div class="bg-light shadow-sm mx-auto" style="width: 70%; height: 200px; border-radius: 21px 21px 0 0;">
        <p class="textAbout">E outra descrição mais engraçadinha ainda. E outra descrição mais engraçadinha ainda. E outra descrição mais engraçadinha ainda.</p>
        </div>
      </div>
</div>
      
<div class="container">
    <span class="over-flow-atras">Nosso Time</span>
    <h2 class="mb-5"><strong>Nosso Time</strong></h2>
   
    <div class="card flex-md-row mb-4 shadow-sm h-md-250">
        <div class="card-body d-flex flex-column align-items-start">
            <strong class="d-inline-block mb-2 text-danger">Desevolvedora</strong>
            <h3 class="mb-3">Ana Eliza Yukimoto de Oliveira</h3>
            <h6 class="card-text mb-auto">Este é um card maior com suporte a texto, em baixo, como uma introdução mais natural ao conteúdo adicional. Este conteúdo é um pouco maior, para demonstração.</p>
            <ul class="list-inline"> 
                <li class="list-inline-item "><a class="footer-link text-danger" href="#"><i class="fab fa-github"></i></a></li>
                <li class="list-inline-item"><a class="footer-link text-danger" href="#"><i class="fab fa-linkedin"></i></a></li>
                <li class="list-inline-item"><a class="footer-link text-danger" href="#"><i class="fab fa-facebook"></i></a></li>
            </ul>
        </div>
        <img class="card-img-right flex-auto d-none d-lg-block" src="assets/img/devs/AnaEliza.jpeg" style="max-width: 180px; object-fit: cover;" alt="Imagem de capa do card">
    </div>
       
    <div class="card flex-md-row mb-4 shadow-sm ">
    <img class="card-img-right flex-auto d-none d-lg-block" src="assets/img/devs/Barros.jpeg" style="max-width: 180px; height: auto;" alt="Imagem de capa do card">
        <div class="card-body d-flex flex-column align-items-start">
            <strong class="d-inline-block mb-2 text-primary">Título do Card</strong>
            <h3 class="mb-3">Gustavo Barros Silva </h3>
            <p>Este é um card maior com suporte a texto, em baixo, como uma introdução mais natural ao conteúdo adicional. Este conteúdo é um pouco maior, para demonstração.</p>
            <ul class="list-inline">
                <li class="list-inline-item"><a class="footer-link text-primary" href="#"><i class="fab fa-github"></i></a></li>
                <li class="list-inline-item"><a class="footer-link text-primary" href="#"><i class="fab fa-linkedin"></i></a></li>
                <li class="list-inline-item"><a class="footer-link text-primary" href="#"><i class="fab fa-facebook"></i></a></li>
            </ul>
        </div>
        
    </div>

    <div class="card flex-md-row mb-4 shadow-sm h-md-250">
        <div class="card-body d-flex flex-column align-items-start">
            <strong class="d-inline-block mb-2 text-success">Desenvolvedor Full Stack</strong>
            <h3 class="mb-3">Gustavo Inacio Lacerda</h3>
            <p class="card-text mb-auto">
            Desde os 12 anos, minha paixão pela programação tem sido uma força motriz em minha vida. Sempre me fascinei por resolver problemas do mundo real e desenvolver soluções inovadoras que tornam o dia a dia das pessoas mais fácil. Atualmente, estou desenvolvendo uma solução de consultoria fitness, combinando tecnologia e bem-estar para ajudar as pessoas a atingirem seus objetivos de saúde e fitness de maneira mais eficiente.
            </p>
            <ul class="list-inline">
                <li class="list-inline-item"><a class="footer-link text-success" href="#"><i class="fab fa-github"></i></a></li>
                <li class="list-inline-item"><a class="footer-link text-success" href="#"><i class="fab fa-linkedin"></i></a></li>
                <li class="list-inline-item"><a class="footer-link text-success" href="#"><i class="fab fa-facebook"></i></a></li>
            </ul>
        </div>
        <img class="card-img-right flex-auto d-none d-lg-block" src="assets/img/devs/Inacio.jpg" style="max-width: 180px; object-fit:cover; transform: scaleX(-1);" alt="Imagem de capa do card">
    </div>


    <div class="card flex-md-row mb-4 shadow-sm ">
    <img class="card-img-right flex-auto d-none d-lg-block" src="assets/img/devs/Natan.jpg" style="max-width: 180px; object-fit: cover;" alt="Imagem de capa do card">
        <div class="card-body d-flex flex-column align-items-start">
            <strong class="d-inline-block mb-2 text-warning">Título do Card</strong>
            <h3 class="mb-3">Natan Rocha Barbosa </h3>
            <p>Este é um card maior com suporte a texto, em baixo, como uma introdução mais natural ao conteúdo adicional. Este conteúdo é um pouco maior, para demonstração.</p>
            <ul class="list-inline">
                <li class="list-inline-item"><a class="footer-link text-warning" href="#"><i class="fab fa-github"></i></a></li>
                <li class="list-inline-item"><a class="footer-link text-warning" href="#"><i class="fab fa-linkedin"></i></a></li>
                <li class="list-inline-item"><a class="footer-link text-warning" href="#"><i class="fab fa-facebook"></i></a></li>
            </ul>
        </div>
        
    </div>

    <div class="card flex-md-row mb-4 shadow-sm h-md-250">
        <div class="card-body d-flex flex-column align-items-start">
            <strong class="d-inline-block mb-2 text-info">Título do Card</strong>
            <h3 class="mb-3">Pedro Gustavo Junior</h3>
            <p class="card-text mb-auto">Este é um card maior com suporte a texto, em baixo, como uma introdução mais natural ao conteúdo adicional. Este conteúdo é um pouco maior, para demonstração.</p>
            <ul class="list-inline">
                <li class="list-inline-item"><a class="footer-link text-info" href="#"><i class="fab fa-github"></i></a></li>
                <li class="list-inline-item"><a class="footer-link text-info" href="#"><i class="fab fa-linkedin"></i></a></li>
                <li class="list-inline-item"><a class="footer-link text-info" href="#"><i class="fab fa-facebook"></i></a></li>
            </ul>
        </div>
        <img class="card-img-right flex-auto d-none d-lg-block" src="assets/img/devs/" style="max-width: 150px; height: auto;" alt="Imagem de capa do card">
    </div>

    </div>
</div>
