<section id="ServiceHeadingSection">
    <div class="container">
        <div class="row">
            <div class="col-12 col-lg-8">

                <div class="service-header--container">
                    <div class="service-header--lables-contaiers">
                        <label class="spot-label-orange">FITNESS</label>
                        <label class="spot-label-green">Novo na pltaforma</label>
                    </div>
                    <h1 class="service-page--service-title">Centro Fitness SCS</h1>
                </div>

                <div class="professional-service-slider--container">
                    <div class="swiper mySwiper">
                        <div class="swiper-wrapper">
                            <div class="swiper-slide professional-service-slider--item">
                                <img src="/assets/img/models/m1.png" alt="">
                            </div>
                            <div class="swiper-slide professional-service-slider--item">
                                <img src="/assets/img/models/m2.png" alt="">
                            </div>
                            <div class="swiper-slide professional-service-slider--item">
                                <img src="/assets/img/models/m3.png" alt="">
                            </div>
                            <div class="swiper-slide professional-service-slider--item">
                                <img src="/assets/img/models/m2.png" alt="">
                            </div>
                            <div class="swiper-slide professional-service-slider--item">
                                <img src="/assets/img/models/m3.png" alt="">
                            </div>
                        </div>

                        <div class="professional-service-slider--button-next"><i class="fa-solid fa-chevron-right"></i></div>
                        <div class="professional-service-slider--button-prev"><i class="fa-solid fa-chevron-left"></i></div>

                        <div class="professional-service-slider--pagination"></div>
                    </div>

                </div>
            </div>
            <div class="col-12 col-lg-4 professional-service-info--container">
                <div class="professional-service-info--social-media-container">
                    <img src="/assets/icons/share.svg" alt="" class="professional-service-info--social-media-icon">
                    <img src="/assets/icons/solar_heart-broken.svg" alt="" class="professional-service-info--social-media-icon">
                    <img src="/assets/icons/location.svg" alt="" class="professional-service-info--social-media-icon">
                </div>
                
                <div class="professional-service-info--features-container">
                    <div class="professional-service-info--feature-item">
                        <div class="professional-service-feature-item--feature-description">
                            <img src="/assets/icons/agenda.svg" alt="" class="professional-service-item--icon">
                            <p class="professional-service-feature--name">Aulas</p>
                        </div>

                        <div class="professional-service-feature--intensity-container">
                            <p class="professional-service-feature--intensity-text">
                                4 por semana 
                            </p>
                        </div>
                    </div>
                    <div class="professional-service-info--feature-item">
                        <div class="professional-service-feature-item--feature-description">
                            <img src="/assets/icons/agenda.svg" alt="" class="professional-service-item--icon">
                            <p class="professional-service-feature--name">Duração</p>
                        </div>

                        <div class="professional-service-feature--intensity-container">
                            <p class="professional-service-feature--intensity-text">
                                30 minutos
                            </p>
                        </div>
                    </div>
                    <div class="professional-service-info--feature-item">
                        <div class="professional-service-feature-item--feature-description">
                            <img src="/assets/icons/paper.svg" alt="" class="professional-service-item--icon">
                            <p class="professional-service-feature--name">Plano de Dieta</p>
                        </div>

                        <div class="professional-service-feature--intensity-container">
                            <p class="professional-service-feature--intensity-text">
                                1 por semana 
                            </p>
                        </div>
                    </div>
                </div>

                <div class="professional-service-info--text-description-container">
                    <p class="professional-service-info--text-description">
                    Um plano de desenvolvimento para atletas de alta performance é essencial para maximizar seu potencial. Com avaliação holística, metas claras, treinamento multidisciplinar. 
                    </p>
                </div>

                <div class="professional-service-info--contact-container">
                    <div class="professional-service-info--contact-item">
                        <img src="/assets/icons/phone.svg" class="professional-service-info--contact-icon">
                        <p class="professional-service-info--contact-text">+55 (11) 98302-0692</p>
                    </div>
                    <div class="professional-service-info--contact-item">
                        <img src="/assets/icons/mail-outline.svg" class="professional-service-info--contact-icon">
                        <p class="professional-service-info--contact-text">fake.email@gmail.com</p>
                    </div>
                    <div class="professional-service-info--contact-item">
                        <img src="/assets/icons/location.svg" class="professional-service-info--contact-icon">
                        <p class="professional-service-info--contact-text">Rua Jabaquara, Nº 3002</p>
                    </div>
                </div>

                <div class="professional-service-info--chat-action-container">
                    <form action="" method="POST">
                        <input type="text" style="display: none" value="<?=!empty($providerId) ? $providerId : ''?>">
                        <button type="submit" class="spot-btn-dark-orange onhover-broom">
                            <span>
                                Entrar em contato pelo Chat
                            </span>
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

<section id="fpDescriptionSection">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="fp-description-title-area row">
                    <h1 class="spot-text-title">Descrição</h1>
                    <p class="spot-text-title-watermark">Descrição</p>
                </div>          
            </div>
        </div>

        <div class="row">
            <p class="fp-description-text">
            Nosso serviço oferece um plano de desenvolvimento sob medida para atletas que buscam alcançar o mais alto nível de excelência em suas respectivas modalidades esportivas. Reconhecendo que cada atleta é único, nossa abordagem é holística e altamente personalizada, visando não apenas maximizar o desempenho atlético, mas também promover o bem-estar geral e o crescimento pessoal.
Avaliação Abrangente: Começamos com uma avaliação detalhada das habilidades físicas, técnicas, táticas, mentais e emocionais de cada atleta. Essa análise profunda nos permite identificar pontos fortes, áreas de melhoria e necessidades individuais específicas.
Metas Claras e Realistas: Junto com o atleta, estabelecemos metas claras, alcançáveis ​​e significativas. Essas metas são elaboradas de forma a serem específicas, mensuráveis, alcançáveis, relevantes e com prazos definidos (SMART), proporcionando uma direção clara para o progresso e aprimoramento contínuos.
Treinamento Multidisciplinar: Nossa equipe de treinadores altamente qualificados e especializados em diversas áreas, como condicionamento físico, técnica, tática, nutrição, psicologia do esporte e recuperação, trabalha em conjunto para fornecer um treinamento abrangente e integrado.
Acompanhamento Personalizado e Feedback Constante: Valorizamos a comunicação aberta e regular com cada atleta. Mantemos um acompanhamento personalizado e oferecemos feedback construtivo para garantir que o plano de desenvolvimento esteja alinhado com as necessidades individuais e que o progresso seja otimizado.
Foco na Saúde Mental e Bem-Estar: Reconhecemos a importância da saúde mental e do bem-estar emocional para o desempenho atlético. Portanto, integramos práticas de gerenciamento de estresse, apoio psicológico e estratégias de autocuidado em nosso programa, promovendo uma abordagem equilibrada para o sucesso esportivo e pessoal.
Flexibilidade e Adaptação: Nosso plano de desenvolvimento é altamente flexível e adaptável. Estamos preparados para ajustar o programa conforme necessário, levando em consideração as mudanças nas circunstância.
            </p>
        </div>
    </div>
</section>


<script src="/assets/javascripts/professional/specificProfessionalPage.js" defer></script>