<div class="container mt-5">
    <div class="row justify-content-center">
        <span class="over-flow-atras text-center">EDITAR CONTA</span>
        <h1 class="mb-5 text-center"><strong>Editar Conta</strong></h1>

        <div class="col-md-5">
            <form class="needs-validation form-forgot" novalidate>

                <div class="text-center mb-3">
                    <img class="img mx-auto d-block rounded-circle" src="https://via.placeholder.com/150" alt="Imagem de capa do card">
                </div>

                <div class="form-group mb-3">
                    <label for="imagem">Selecionar Imagem para Editar</label>
                    <input type="file" class="form-control-file" id="imagem" accept="image/*" required>
                </div>

                <div class="form-group mb-3">
                    <label for="name">Nome Completo</label>
                    <input type="text" class="form-control" id="name" autocomplete="name" required>
                </div>

                <div class="form-group mb-3">
                    <label for="email">E-mail</label>
                    <input type="email" class="form-control" id="email" autocomplete="email"  required>
                </div>
                <div class="form-group mb-3">
                    <label for="phone">Telefone ou Celular</label>
                    <input type="number" class="form-control" id="phone" autocomplete="phone" required>
                </div>

                <button type="submit" class="btn btn-primary btn-block mb-5">Salvar Edição</button>
            </form>
        </div>
    </div>

    <div class="row justify-content-center consultancies">
        <h3 class="mb-5 text-center">Minhas Consultorias</h3>

        <div class="col-sm-4 col-md-3">
            <div class="card">
                <img class="card-img-top" src="https://via.placeholder.com/150" alt="Imagem de capa do card">
                <div class="card-body">
                    <h5 class="card-title text-center">Consultoria 1</h5>
                    <p class="card-text text-center">Descrição 1</p>
                    <div class="text-center"> 
                        <a href="#" class="btn btn-primary btn-block">Editar</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-sm-4 col-md-3">
            <div class="card">
                <img class="card-img-top" src="https://via.placeholder.com/150" alt="Imagem de capa do card">
                <div class="card-body">
                    <h5 class="card-title text-center">Consultoria 2</h5>
                    <p class="card-text text-center">Descrição 2</p>
                    <div class="text-center"> 
                        <a href="#" class="btn btn-primary btn-block">Editar</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-sm-4 col-md-3">
            <div class="card">
                <img class="card-img-top" src="https://via.placeholder.com/150" alt="Imagem de capa do card">
                <div class="card-body">
                    <h5 class="card-title text-center">Consultoria 3</h5>
                    <p class="card-text text-center">Descrição 3</p>
                    <div class="text-center"> 
                        <a href="#" class="btn btn-primary btn-block">Editar</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
