<div class="container mt-5">
    <div class="row justify-content-center">
        <span class="over-flow-atras text-center">EDITAR CONTA</span>
        <h1 class="mb-5 text-center"><strong>Editar Conta</strong></h1>

        <div class="col-md-5">
            <form class="needs-validation form-forgot" novalidate>

                <div class="text-center mb-3">
                    <img class="img mx-auto d-block rounded-circle img-perfil" src="/assets/img/perfil_profissional.jpg" alt="Imagem de capa do card">
                </div>

                <div class="text-center mb-5">
                    <label for="imagem">Selecionar Imagem para Editar</label>
                    <input type="file" class="form-control-file" id="imagem" accept="image/*" required>
                </div>

                <div class="form-group mb-3">
                    <label for="name">Nome Completo</label>
                    <input type="text" class="form-control" id="name" autocomplete="name" required>
                </div>

                <div class="form-group mb-3">
                    <label for="email">E-mail</label>
                    <input type="email" class="form-control" id="email" autocomplete="email"  required>
                </div>
                <div class="form-group mb-3">
                    <label for="phone">Telefone ou Celular</label>
                    <input type="number" class="form-control" id="phone" autocomplete="phone" required>
                </div>
                <div class="form-group mb-3">
                    <label for="desc">Descrição</label>
                    <textarea class="form-control" id="desc" autocomplete="desc" required></textarea>
                </div>

                <button type="submit" class="btn btn-primary btn-block mb-5">Salvar Edição</button>
            </form>
        </div>
    </div>

    <div class="justify-content-center">

        <h1 class="mb-5"><strong>Minhas Consultorias</strong></h1> 

        <div class="row">
            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="card">
                    <img class="card-img-top img-fluid" src="/assets/img/models/m1.png" alt="Imagem de capa do card">
                    <div class="card-body">
                        <h5 class="card-title text-center">Consultoria 1</h5>
                        <p class="card-text text-center">Descrição 1</p>
                        <a href="/consulting/new" class="btn btn-primary btn-block">Editar</a>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="card">
                    <img class="card-img-top img-fluid" src="/assets/img/models/m2.png" alt="Imagem de capa do card">
                    <div class="card-body">
                        <h5 class="card-title text-center">Consultoria 2</h5>
                        <p class="card-text text-center">Descrição 2</p>
                        <a href="/consulting/new" class="btn btn-primary btn-block">Editar</a>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="card">
                    <img class="card-img-top img-fluid" src="/assets/img/models/m3.png" alt="Imagem de capa do card">
                    <div class="card-body">
                        <h5 class="card-title text-center">Consultoria 3</h5>
                        <p class="card-text text-center">Descrição 3</p>
                        <a href="/consulting/new" class="btn btn-primary btn-block">Editar</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>