<?php var_dump(get_defined_vars()); var_dump([
    'profile_photo' => $userData['profile_photo'] ?? null,
    'user_name' => $userData['user_name'] ?? 'Nome não disponível',
    'email' => $userData['email'] ?? 'E-mail não disponível',
    'phone' => $userData['phone'] ?? 'Telefone não disponível',
]);
?>

<div class="container">
    <div class="row justify-content-center">
        <span class="over-flow-atras text-center">MINHA CONTA</span>
        <h1 class="mb-5 text-center"><strong>Minha Conta</strong></h1>

        <div class="col-md-5 mb-5">
            <form class="form-forgot">
                <div class="text-center mb-3">
                    <img class="img mx-auto d-block rounded-circle img-perfil"src="<?= isset($userData['profile_photo']) ? htmlspecialchars($userData['profile_photo']) : ''; ?>" alt="Imagem de capa do card">
                </div>

                <div class="form-group mb-3">
                    <input type="text" class="form-control name" id="name" autocomplete="name" value="<?= isset($userData['user_name']) ? htmlspecialchars($userData['user_name']) : ''; ?>" readonly>
                </div>

                <div class="form-group mb-3">
                    <label for="email">E-mail</label>
                    <input type="email" class="form-control" id="email" autocomplete="email" value="<?= isset($userData['email']) ? htmlspecialchars($userData['email']) : ''; ?>" readonly>
                </div>

                <div class="form-group mb-3">
                    <label for="phone">Telefone ou Celular</label>
                    <input type="number" class="form-control" id="phone" autocomplete="phone" value="<?= isset($userData['phone']) ? htmlspecialchars($userData['phone']) : ''; ?>" readonly>
                </div>
            </form>
        </div>
 

    <div class="justify-content-center">

        <div class="row align-items-center mb-5">
            <div class="col">
                <h1 class=" "><strong>Minhas Consultorias</strong></h1> 
            </div>

            <div class="col-auto d-flex justify-content-center">
                <a href="/consulting/edit?id=" class="btn btn-primary btn-edit-profile"> Editar Conta <i class="fas fa-edit"></i></a>
            </div>

            <div class="col-auto d-flex justify-content-center">
                <button class="btn btn-outline-light" type="button"><a href="/consulting/new" class="nav-link active"> Nova Consultoria</a></button>
            </div>
        </div>
        
    
        <div class="row">
            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="card">
                    <img class="card-img-top img-fluid" src="/assets/img/models/m1.png" alt="Imagem de capa do card">
                    <div class="card-body">
                        <h5 class="card-title text-center">Consultoria 1</h5>
                        <p class="card-text text-center">Descrição 1</p>
                        <div class="row align-items-center">
                            <div class="col">
                                <a href="/consulting/show" class="btn btn-primary btn-block btn-view">Visualizar</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="card">
                    <img class="card-img-top img-fluid" src="/assets/img/models/m2.png" alt="Imagem de capa do card">
                    <div class="card-body">
                        <h5 class="card-title text-center">Consultoria 2</h5>
                        <p class="card-text text-center">Descrição 2</p>
                        <div class="row align-items-center">
                            <div class="col">
                                <a href="/consulting/show" class="btn btn-primary btn-block btn-view">Visualizar</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="card">
                    <img class="card-img-top img-fluid" src="/assets/img/models/m3.png" alt="Imagem de capa do card">
                    <div class="card-body">
                        <h5 class="card-title text-center">Consultoria 3</h5>
                        <p class="card-text text-center">Descrição 3</p>
                        <div class="row align-items-center">
                            <div class="col">
                                <a href="/consulting/show" class="btn btn-primary btn-block btn-view">Visualizar</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
