
<div class="container">
    <div class="row justify-content-center">
        <h1 class="text-center"><strong>Minha Conta</strong></h1>

        <div class="col-md-5 mb-5">
            <form>
                <div class="text-center mb-3">
                    <img class="img mx-auto d-block rounded-circle img-perfil" src="<?= isset($user['profile_photo']) ? '/image_uploads/' . htmlspecialchars($user['profile_photo']) : ''; ?>" alt="Imagem de perfil">
                </div>

                <div class="form-group mb-3">
                    <input type="text" class="form-control name" id="name" autocomplete="name" readonly value="<?= htmlspecialchars($user['user_name']); ?>">
                </div>

                <div class="form-group mb-3">
                    <label for="email">E-mail</label>
                    <input type="email" class="form-control" id="email" autocomplete="email" readonly value="<?= htmlspecialchars($user['email']); ?>">
                </div>

                <div class="form-group mb-3">
                    <label for="phone">Telefone ou Celular</label>
                    <input type="text" class="form-control" id="phone" autocomplete="phone" readonly value="<?= htmlspecialchars($user['phone']); ?>">
                </div>
            </form>
        </div>
    </div>

    <div class="justify-content-center">

        <div class="row align-items-center mb-5">
            <div class="col">
                <h1 class=" "><strong>Minhas Consultorias</strong></h1> 
            </div>

            <div class="col-auto d-flex justify-content-center">
                <a href="/consulting/edit?id=" class="btn btn-primary btn-edit-profile"> Editar Conta <i class="fas fa-edit"></i></a>
            </div>

            <div class="col-auto d-flex justify-content-center">
                <button class="btn btn-outline-light" type="button"><a href="/consulting/new" class="nav-link active">Nova Consultoria</a></button>
            </div>
        </div>
        
        <?php foreach ($consultings as $consulting): ?>
            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="card">
                    <img class="card-img-top img-fluid" src="/image_uploads/<?= htmlspecialchars($consulting['image_path']); ?>" alt="Imagem de capa do card">
                    <div class="card-body"> 
                        <h5 class="card-title text-center"><?= htmlspecialchars($consulting['consulting_name']); ?></h5>
                        <p class="card-text text-center"><?= htmlspecialchars($consulting['description']); ?></p>
                        <div class="row align-items-center">
                            <div class="col">
                                <a href="/consulting/show?id=<?= htmlspecialchars($consulting['consulting_id']); ?>" class="btn btn-primary btn-block btn-view">Visualizar</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
        
    </div>
</div>
