<!DOCTYPE html>
<html lang="pt-BR">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Spotfit</title>
	<link rel="icon" href="/assets/img/iconLogo.png" type="image/x-icon">

	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
	<link rel="stylesheet" href="/assets/stylesheets/application.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
	<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;700&display=swap" rel="stylesheet">

	<?= $this->load_controller_css() ?>
	
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
	<script src="/assets/javascripts/application.js" defer></script>
	<?= $this->load_controller_js() ?>
</head>

<body class="body">

	<nav class="navbar navbar-expand-lg navbar-dark fixed-top">
		<div class="container">
			<a class="navbar-brand" href="#">
				<img src="/assets/img/logo.png" width="100" height="50" alt="">
			</a>

			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#contentNavbar" aria-controls="contentNavbar" aria-expanded="false" aria-label="Toggle Nav">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="contentNavbar">
				<ul class="navbar-nav mx-auto">
					<li class="nav-item active">
						<a class="nav-link" href="/landing_page">Home </a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="#">Profissionais</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="#">Sobre</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="/faq">Contato</a>
					</li>
				</ul>

				<button class="btn btn-sm btn-outline-light" type="button">Login</button>

				<button class="btn btn-sm btn-primary" type="button">Crie sua conta</button>
				
			</div>
		</div>
	</nav>

	<?= $this->content() ?>

	<footer class="footer pt-4 my-md-5 pt-md-5 text-light">
		<div class="container">
			<div class="row">
				<div class="col-6 col-md">
					<img class="mb-2" src="/assets/img/logo.png" alt="" width="100" height="50">
					<small class="d-block mb-4">Encontre os benefícios físicos e mentais de uma vida ativa e saudável</small>
				</div>
				<div class="col-6 col-md ">
					<h5>Mapa do Site</h5>
					<ul class="list-unstyled ">
						<li><a class="footer-link" href="/landing_page">Home</a></li>
						<li><a class="footer-link" href="#">Profissionais</a></li>
						<li><a class="footer-link" href="#">Sobre</a></li>
						<li><a class="footer-link" href="#">Login / Cadastra-se</a></li>
					</ul>
				</div>
				<div class="col-6 col-md">
					<h5>Suporte</h5>
					<ul class="list-unstyled">
						<li><a class="footer-link"  href="/faq">FAQ</a></li>
						<li><a class="footer-link"  href="/faq">Centro de Ajuda</a></li>
					</ul>
				</div>
				<div class="col-6 col-md">
					<h5>Redes Sociais</h5>
					<ul class="list-inline">
						<li class="list-inline-item"><a class="footer-link" href="#"><i class="fab fa-twitter"></i></a></li>
						<li class="list-inline-item"><a class="footer-link" href="#"><i class="fab fa-instagram"></i></a></li>
						<li class="list-inline-item"><a class="footer-link" href="https://www.facebook.com/seuusuario"><i class="fab fa-facebook"></i></a></li>
					</ul>
				</div>

				<div class="list-inline d-flex justify-content-between border-top">
					<small class="d-inline mb-4 text-secondary"> &copy; 2024 - Spotfit</small>
					<div class="ml-auto">
						<div class="d-inline mb-4 mx-4 text-secondary">Termos de Uso</div>
						<div class="d-inline mb-4 text-secondary">Política de Privacidade</div>
					</div>
				</div>

			</div>
		</div>
	</footer>

	<!-- jQuery e Bootstrap JS -->
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</body>
</html>