<!DOCTYPE html>
<html lang="pt-BR">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Spotfit</title>
	<link rel="icon" href="/assets/img/iconLogo.png" type="image/x-icon">

	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
	<link rel="stylesheet" href="/assets/stylesheets/application.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
	<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;700&display=swap" rel="stylesheet">
	<!-- Swiper-->
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"/>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" inategrity="sha512-R26F1BgBpW2Mx2iu49c2ylPt19q0EsP5B2Oj+XJbRtzSftCf9oBd2/vcsDBk9H4RYK6cnfB41RSNOyhGRb6DpA==" crossorigin="anonymous" referrerpolicy="no-referrer" />


	<?= $this->load_controller_css() ?>
	
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous" defer></script>
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/cleave.js@1.6.0/dist/cleave.min.js"></script>
	<script src="/assets/javascripts/application.js" defer></script>
	<!--Swiper -->
	<script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js" defer></script>
	<script src="https://kit.fontawesome.com/a638ecb17e.js" crossorigin="anonymous" defer></script>

	<?= $this->load_controller_js() ?>
</head>

<body class="body" data-bs-theme="dark">

	<nav class="navbar navbar-expand-lg navbar-dark fixed-top">
		<div class="container">
			<a class="navbar-brand" href="/landing_page">
				<img src="/assets/img/logo.png" width="100" height="50" alt="">
			</a>

			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="navbarScroll">
				<ul class="navbar-nav mx-auto">
					<li class="nav-item active">
						<a class="nav-link" href="/landing_page">Home </a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="/consulting">Profissionais</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="/planview">Planos</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="/about">Sobre</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="/faq">Contato</a>
					</li>
				</ul>

				<?php if(isset($_SESSION['auth']) && $_SESSION['auth']) { ?>
					<a href="/profile?id=<?= htmlspecialchars($_SESSION['user_id']) ?>" class="btn btn-primary"><i class="fas fa-user"></i> Meu perfil</a>
					<a href="/sign_in/logout" class="btn btn-danger ms-3"><i class="fas fa-sign-out-alt"></i></a>
				<?php } else { ?>
					<button class="btn btn-sm btn-outline-light" type="button"><a href="/sign_in" class="nav-link active">Login</a></button>
					<button class="btn btn-sm btn-primary" type="button"><a href="/sign_up" class="nav-link active">Crie sua conta</a></button>
				<?php } ?>

				
			</div>
		</div>
	</nav>

	<?= $this->content() ?>

	<footer class="footer pt-4 my-md-5 pt-md-5 text-light">
		<div class="container">
			<div class="row">
				<div class="col-6 col-md">
					<img class="mb-2" src="/assets/img/logo.png" alt="" width="100" height="50">
					<small class="d-block mb-4">Encontre os benefícios físicos e mentais de uma vida ativa e saudável</small>
				</div>
				<div class="col-6 col-md ">
					<h5>Mapa do Site</h5>
					<ul class="list-unstyled ">
						<li><a class="footer-link" href="/landing_page">Home</a></li>
						<li><a class="footer-link" href="/consulting">Profissionais</a></li>
						<li><a class="footer-link" href="/planview">Planos</a></li>
						<li><a class="footer-link" href="/about">Sobre</a></li>
						<li><a class="footer-link " href="/sign_up" >Login / Cadastra-se</a></li>
					</ul>
				</div>
				<div class="col-6 col-md">
					<h5>Suporte</h5>
					<ul class="list-unstyled">
						<li><a class="footer-link"  href="/faq">FAQ</a></li>
						<li><a class="footer-link"  href="/faq">Centro de Ajuda</a></li>
					</ul>
				</div>
				<div class="col-6 col-md">
					<h5>Redes Sociais</h5>
					<ul class="list-inline">
						<li class="list-inline-item"><a class="footer-link" href="#"><i class="fab fa-twitter"></i></a></li>
						<li class="list-inline-item"><a class="footer-link" href="#"><i class="fab fa-instagram"></i></a></li>
						<li class="list-inline-item"><a class="footer-link" href="#"><i class="fab fa-facebook"></i></a></li>
					</ul>
				</div>

				<div class="list-inline d-flex justify-content-between border-top">
					<small class="d-inline mb-4 text-secondary"> &copy; 2024 - Spotfit</small>
					<div class="ml-auto">
						<div class="d-inline mb-4 mx-4 text-secondary">Termos de Uso</div>
						<div class="d-inline mb-4 text-secondary">Política de Privacidade</div>
					</div>
				</div>

			</div>
		</div>
	</footer>
</body>
</html>